### ISSUE TITLE
Use buildroot cache to speed up builds

### ISSUE THREAD

**Issue by angelnu** [jens-maus/RaspberryMatic#1060]
**Is your feature request related to a problem? Please describe.**
The CI builds take quite long since the github actions runners do not have a lot of CPUs. This makes each PR to take 5+ hours

**Describe the solution you'd like**
Use buildroot cache and store the cache in github artifacts so it survives across runs.

**Describe alternatives you've considered**
Dummy builds which are VERY fast but only allow CI test, not building real images.

**Additional context**
https://buildroot.org/downloads/manual/manual.html#ccache

**Comment by jens-maus** [comment]
A speedup of the CI builds would be highly desireable, yes. But I am still unsure 

1. if this does not affect the build consistency in any way if we always carry on an old ccache from build to build
2. how and where exactly to store the ccache in the artifacts section. This would of course mean we would have to store the ccache in an old build artifact and then pick it up later
3. we would have to keep a ccache per platform and thus could easily reach the maximum build artifact space. That's the reason why in the workflows we have a purge artifacts step, btw

But of course, feel try to come up with a solution or even PR as I would really appreciate it if we could bring down build times significantly!

**Comment by jens-maus** [comment]
Ok, the latest master now has ccache support enabled. Thought I didn't expect it to work here with the GutHub runners (due to the limited cache space) it seem to have worked out fine. Now the build times in the runners are down to from 6h to 3h! So thanks for the suggestion so that I gave it a try now :) next thing to speedup the build would be to host own runners and use them instead. This could then potentially increase build times once nore of course ;) but for the moment I am quite happy. So thx again!

**Comment by angelnu** [comment]
Cool that you gave it a try and it worked out!

When I am testing just the ci currently the deployment test does not work with the dummy build so the speed up is appreciated
