### ISSUE TITLE
Add Helm chart to deploy RaspberryMatic in Kubernetes

### ISSUE THREAD

**Issue by angelnu** [jens-maus/RaspberryMatic#1090]
**Is your feature request related to a problem? Please describe.**
After adding the OCI images a Helm chart is helpful to deploy this image into Kubernetes

**Describe the solution you'd like**
I will provide the Helm chart and a set of GitHub actions to create the required repository

**Describe alternatives you've considered**
Manually install the OCI to Kubernetes

**Additional context**
PR next

**Comment by angelnu** [comment]
@jens-maus - please notice that the Helm chart cannot be build with a PR -> it required access to the GITHUB_TOKEN secret to upload to the gh_pages - see https://medium.com/@stefanprodan/automate-helm-chart-repository-publishing-with-github-actions-and-pages-8a374ce24cf4

You also need to create the gh_pages branch as I listed in the PR.

- example of me manually triggering the Workflow: https://github.com/angelnu/RaspberryMatic/actions/runs/506192808
- example of the workflow being triggered by adding a tag: https://github.com/angelnu/RaspberryMatic/actions/runs/506102865
- example of the resulting chart: https://github.com/angelnu/RaspberryMatic/tree/gh-pages

**Comment by jens-maus** [comment]
Thanks @angelnu for working on a better Kubernetes integration of RaspberryMatic. I do have to say, that I never tried Kubernetes before and I also don't have any experience with helm, whatsoever. So please forgive me if I might have ask obvious questions here:

Why is a dedicated gh_pages branches required at all for helm? What is the motivation behind this? So far I have avoided to use gh_pages at all and I am still unsure if we do really require it at all.

Please note that I have registered at artifacthub.io now. My user name is "jens-maus" like here in GitHub. So please make me an owner of the RaspberryMatic org there so that I can help organizing it.

**Comment by angelnu** [comment]
>  do have to say, that I never tried Kubernetes

There is always a first for everything - :-D Fell free to ask/dig as much as you want or stay in the side - to be honest I am not sure how many others run with K8S at their homes but microk8s from Ubuntu is making it quite easy to set up clusters with HA so maybe this increase with the time.

> Why is a dedicated gh_pages branches required at all for helm? What is the motivation behind this? So far I have avoided to use gh_pages at all and I am still unsure if we do really require it at all.

It is not really a requirement per se from Helm but the automation generating the index has to know where the files will be located. Also as a good practice they avoid modifying the master branch and only write to a disposable branch.

Most projects actually put the generated charts in a different git repository so if in the future you consider that you might want to use the GitHub pages we could put them in a RaspberryMatic-charts own repo. Actually in this direction is where the idea of using a git organisation helps to find the related github repos (to separate them from others we work). But for RaspberryMatic this might be overkill and just using a RaspberryMatic- prefix is good enough...

Please notice that the GitHub branch/repo where we put the charts to should have a Readme for those searching the chart in artifacthub.io .

> Please note that I have registered at artifacthub.io now. My user name is "jens-maus" like here in GitHub. So please make me an owner of the RaspberryMatic org there so that I can help organizing it.

Thanks - you should see the org now when you go to the Control Panel - I transferred there the test one until we have this working in your GitHub org.

**Comment by jens-maus** [comment]
> > Why is a dedicated gh_pages branches required at all for helm? What is the motivation behind this? So far I have avoided to use gh_pages at all and I am still unsure if we do really require it at all.
> 
> It is not really a requirement per se from Helm but the automation generating the index has to know where the files will be located. Also as a good practice they avoid modifying the master branch and only write to a disposable branch.
> 
> Most projects actually put the generated charts in a different git repository so if in the future you consider that you might want to use the GitHub pages we could put them in a RaspberryMatic-charts own repo. Actually in this direction is where the idea of using a git organisation helps to find the related github repos (to separate them from others we work). But for RaspberryMatic this might be overkill and just using a RaspberryMatic- prefix is good enough...
>
> Please notice that the GitHub branch/repo where we put the charts to should have a Readme for those searching the chart in artifacthub.io .

It's fine to use the gh_pages branch for this I have not planned to use it otherwise. I just wonder why it have to be the gh_pages branch and not some other arbitrary branch? Does it require some direct http access?


> > Please note that I have registered at artifacthub.io now. My user name is "jens-maus" like here in GitHub. So please make me an owner of the RaspberryMatic org there so that I can help organizing it.
> 
> Thanks - you should see the org now when you go to the Control Panel - I transferred there the test one until we have this working in your GitHub org.

Thanks, I have accepted the invitation. Is there a possibility that you assign me full owner rights to this RaspberryMatic artifacthub.io organization, please?

**Comment by angelnu** [comment]
> It's fine to use the gh_pages branch for this I have not planned to use it otherwise. I just wonder why it have to be the gh_pages branch and not some other arbitrary branch? Does it require some direct http access?

Yes, it does - and the automation expects the same other in github to be present in the public webserver.

> Thanks, I have accepted the invitation. Is there a possibility that you assign me full owner rights to this RaspberryMatic artifacthub.io organization, please?

I am not aware of roles in artifacthub.io organizations - is there anything you miss? If you want to stay single mainteiner there you can remove me once we have the base setup working

**Comment by jens-maus** [comment]
> I am not aware of roles in artifacthub.io organizations - is there anything you miss? If you want to stay single mainteiner there you can remove me once we have the base setup working

I can't change anything regading the RaspberryMatic organization AFAICS, not the URL, nor the description, etc.. I can only "LEAVE" it.  Or should I somehwat "Claim ownership"? Sorry, if I am asking obvious things, but I still have trouble understanding all dependencies here....

**Comment by angelnu** [comment]
I also can only "leave" and I cannot set any settings for you.

Do you see the settings tab?

I have enabled fine-granular settings but I did not change the default which is the owner are all users of the org

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/4406403/105645967-69a17f00-5e9d-11eb-8a48-01de4d1e0565.png">

**Comment by jens-maus** [comment]
Ah, thanks. Now I got it. My mistake! perfect. So gimme some time to wade through all this and then I will check the PR and all this gh_pages stuff ASAP.

**Comment by angelnu** [comment]
Please check specially the helm/Raspberrymatic/chart.yaml since that contains the chart description, license, logo, etc.

The GitHub Actions are also relevant.

The templates folder is mostly the template generated by Helm but Deployment.py has the ports needed by RaspberryMatic - you might want to see I did not miss any.

Let me know if you need any help.

**Comment by jens-maus** [comment]
Ok, I have now merged your PR and also tried to setup everything correctly in artifacthub.io. I even managed to get this approved as a "Verified Publisher". Even thought I don't use K8s and Helm myself I do hope that this works now as expected. If you can, please invest more time into the Kubernetes Wiki documentation part, potentially covering even a basic K8s setup with standard amd64 hardware in mind. And for a more easy start, it would be perhaps a good idea to add a minor introduction to K8s and the benefits, etc. of it compared to bare docker.

And please check that now everything works as expected. According to your TODO list above only a basic README seems to be missing, which you wanted to add to the gh_pages branch. If so, please do so...

**Comment by angelnu** [comment]
Nice work @jens-maus - I tried the uploaded chart in my cluster and it did deploy fine in my test zone so all the basics are there.

I will move it to my prod to ensure is fine and extend the Wiki . A basic single node microk8s is actually just a single snap command to install. In fact I have seen that there is a GitHub action available to deploy microk8s so I can as well add a workflow to test with it (triggered each time a new helm chart is being built).

**Comment by jens-maus** [comment]
that sounds great @angelnu. I am, however, mostly insterested in more detailed basic documentation on K8s in the RaspberryMatic wiki. I would really like to get more users into that topic and have documentation on docker/oci and kubernetes as easy and basic as possible.. And of course, if there is a microk8s github action, go ahead in sending in a PR along the still missing README in the gh_pages branch....

**Comment by angelnu** [comment]
It was a, in addition to, not instead ;-)

**Comment by angelnu** [comment]
@jens-maus - I wrote the wiki instructions, could you (or anyone reading this) give them a try? The should not require previous Kubernetes knowledge.

**Comment by jens-maus** [comment]
OK, I merged your PRs. So I think we are done here, right? What I still don't understand is the actual release process of these helm charts? Currently it is always version 0.1? shouldn't we use the typical RaspberryMatic versioning scheme (e.g. 3.55.10.20210126) for publishing the helm charts as well? And do we really need them to be re-generated with every CI run?

Perhaps we also need a release GitHub workflow now which could be automatically triggered by me by creating a new official release tag in the Releases section. Even for the plain docker/OCI this might be required now, perhaps. What do you think?

**Comment by angelnu** [comment]
The automation should create a new Helm chart called 3.55.10 once you tag it. You can also trigger the creation of it manually.

So when you are ready for an official release we need:

1. create an official "latest" OCI image. Currently we only have snapshot. You need to use the `Set OCI tag` workflow to create the "lastest" OCI tag
2. create an official Helm Chart. Currently we only have 0.1 (which is same as snapshot but Helm requires semantic versions). once you tag `Helm chart - build for tag`will build a 3.xx.xx chart.

I can add a workflow automatically update the OCI latest when you tag in the same way I did for Helm.

**Comment by jens-maus** [comment]
> IMO I think we are ready for an official release so we can also test that path (let us call it a Beta from the OCI RaspberyMatic platform)

Yes, I also think it is time to consider a new RaspberryMatic release. However, I do want to get the last final bits sorted out before doing a general new release. And since this OCI and Kubernetes is a complete new platform and also the home-assistant-addon is completly new I would like to first get things sorted out. Especially the OCI/Docker/Kubenertes platform changed my general release procedures which have been mainly completely manual in the past. Even the final release archives were build on my own server at home rather than on GitHub Actions. But this does not seem to be possible anymore with OCI/Docker and Kubernetes in mind. The final release of these platforms completly relies on GitHub Actions to perform the necessary tasks. So we would have to sort out a completely new release procedure now, which should also take care of the traditional release archives for all the other platforms. And this is where I am still unsure how to proceed now. We have a lot of new GitHub workflows in place now and especially the manual ones (especially the helm chart ones) are the ones that still confuse me. So we would need a much clearer release procedure definition and potentially documentation now, I guess.

So my proposal would be that you please add some short documentation on the current release procedure for OCI/Docker and Kubernetes/Helm to DEVELOPMENT.md. Then I can revisit this and we can think about the potential of an automatic GitHub workflow just for performing the final release. The previous procedure I used was more or less:

1. Manually create a new "Draft" release under the "Releases" part in GitHub
2. Manually write the ChangeLog based on the performed changes since the last release, actually saving it as a "Draft release"
3. Create the final release archives for all platforms on my own server using `make release-all` and wait until done (about 5-6 hours).
4. Manually upload the release archives to the Draft release
5. Manually embed the SHA256 checksum of each release archive in the Release ChangeLog part of the release draft
6. If done, press "Publish" in the draft release to officially release the new 3.XX.XX.YYYMMDD and let GitHub add the tag in git automatically.

But now with OCI/Docker, Kubernetes and HomeAssistant Add-On in mind this change this mainly manual procedure dramatically. The question is, if we can create an semi-automatic workflow that will more or less most of the above automatically, just requiring me to create the ChangeLog manually as usual. Do you have any idea?

> I can add a workflow automatically update the OCI latest when you tag in the same way I did for Helm.

I would really prefer if we would have a single workflow that does all the release magic automatically instead of having to run several different workflows or still having to create the other platform archives manually as a side job...

> something I would propose to consider is to pick up semantic version : so `3.55.10.20210126` would become `3.55.10-alpha.20210126`. This way the helm chart could be done this way as well. Helm takes care of updating production images (those that do not have the dash)

No, I don't have plans to change the versioning scheme of RaspberryMatic. Especially not if it is only required for the helm charts which only a few people will be probably interested at all. So either we just use the official OCCU version each time for the helm chart (only e.g. "3.55.10") and in case we do alpha/beta charts we use the "3.55.10-YYYYMMDD" but only to please the helm logic.

> **UPDATE 2**:
> I noticed that we lost the workflow to manually tag an OCI image - we will need to add. I would like to do it as for the Helm chart based on the tagging. Do you agree ?

As said above, I would prefer if we could first sort out how to proceed with the general release procedure from now on.  I still want to keep the unified release cycle of almost once per month and have a unified release for all supported platforms (incl. the HA Add-on) if possible. Thus, we need a clear plan how to do that in future. And that's where I am still unsure...

> **Update 3**
> 
> I do not find a simple way to re-tag an existing multiarch OCI to `latest` -> so we would need to add the code to the CI to also tag the build with `latest` when you tag the official release.

That's exactly what I would like to have an official "release" workflow to perform. When an official release is tagged or manually triggered by me, I would like to have this workflow also tag the docker/OCI archives as "latest" and "3.XX.XX.YYYYMMDD" to make it clear that this is an official release. All the other builds (from CI) of the docker/OCI should continue to carry the "snapshot" tag and have the "3.XX.XX.YYYYMMDD-SHA9" to make clear these are experiemental builds.
One problem with that is, however, that

1. the amount of OCI/docker images/versions already increased quite a lot in the GitHub Container Registry section (https://github.com/users/jens-maus/packages/container/package/raspberrymatic) during the last weeks. It already lists 240 "versions"?!? And I think apart from hitting a storage limit soon, it would still be nice to get old/obsolete versions/packages cleared in the ghcr.io space. Unfortunately I didn't find a GitHub Action yet that allows to remove old package versions because ghcr.io is still in beta phase as it seems...
2. I am still unsure if putting "snapshot" and "latest/stable" container versions/packages into the same "raspberrymatic" ghcr.io space is a good thing. The ghcr.io logic seem to always show the latest pushed package at the very top regardless of the tag. So as soon as a new snapshot or CI build is generated it will show that one, thus hide the "latest" tagged version. So perhaps we need a separate "raspberrymatic-snapshot" space/package in ghcr.io just for the snapshots? What do you think? 

> So the flow would be:
> 
> 1. you push a tag 3.xx.yy.zz
> 2. CI builds and push OCI with tags `3.xx.yy.zz` and `latest`
> 3. Helm CI build chart version 3.xx.yy pointing to OCI 3.xx.yy.zz

And what about the traditional release archives of the other platforms (e.g. rpi3?). And how should I then then prepare the ChangeLog and the new Releases page in the Releases section? Best would be if there is a possibility I can draft the release as usual, then press "publish" and then the release workflow starts, generates all archives, OCI/Docker images, helm charts, etc. and then put the generated release archives automatically in the new release page under "Assets"....

**Comment by angelnu** [comment]
Ok, then let me start a PR of how the new fully automated CI could look like in the Development,md and we can iterate on it. Once we are ok with the high level approach then we can start implementing according to it.

After reading your comments I would think in these big lines:
1. you create a release draft. TBD: is there value in https://github.com/actions/create-release ?
   - GitHub tags the current branch - Example: 3.xx.yy.zz
2. CI builds and push **all images*. Non-OCI is uploaded to the release, OCI builds with tags 3.xx.yy.zz and latest.
   - NOTE: after this point people on Docker using latest will get the update
3. CI builds chart version 3.xx.yy pointing to OCI 3.xx.yy.zz
   - NOTE: after this point people on Kubernetes using >3 will get the update
6. you publish the release

What I do not like from GitHub Workflows is that there does not seem to be a good way to reuse job steps. I expect the a lot of commonality between the CI, snapshots and release workflows. But a common workflow with a lot of _if_ is not great either...

>  I am still unsure if putting "snapshot" and "latest/stable" container versions/packages into the same "raspberrymatic" ghcr.io space is a good thing. 

This is what usually projects do - typically you document in the package list what is the tag strategy for the repository. Also in the release you can point what is the official tag. That being said, there is no real reason why we would not want to put dev versions of the container to a different package repository.

I am not aware of any storage limits at this point - Docker Hub tends to delete unused ones after a while

**Comment by angelnu** [comment]
any feedback on the above @jens-maus - I will try to do it over the weekend (had very little time during the week)

**Comment by jens-maus** [comment]
> After reading your comments I would think in these big lines:
> 
> 1. you create a release draft. TBD: is there value in https://github.com/actions/create-release ?

If this works out with actions/create-release this could indeed be helpfull. We could actually have a manual (only workflow_dispatch) create-release workflow that creates the release draft right away with a predefined body template put into the repository itself. This is something I could actually work on.

>    * GitHub tags the current branch - Example: 3.xx.yy.zz

GitHub will only really put the tag into the repository (git) as soon as the release is published and not via drafting release.

> 2. CI builds and push *_all images_. Non-OCI is uploaded to the release, OCI builds with tags 3.xx.yy.zz and latest.
>    * NOTE: after this point people on Docker using latest will get the update

While this sounds fine to me, we still have the current issue that the build of all platforms takes to long (>6h) again. Even with the ccache in place it does not finish in time. Either GitHub runner performance changed to some extend or the issue might be that the ccache has way too much cache misses. Some ccache caches are almost 2GB large (as can be seen in the Action output) and that means that there is not enough space (max 5GB from GitHub for caches) for all ccaches (we have 10 platforms!). I am still trying to setup self hosted runners, but there are some yet unresolved dependencies and I am still unsure if perfomance wise this will help to finish the builds in reasonable time. Furthermore, as per GitHub documentation and my research self-hosted runners on public repos have some security constraints and requires to make sure that no pull-request will run on the self-hosted runners or otherwise things could be executed on the runners that compromise the security on the runner hosts. But I am on the topic and perhaps I do have to revert the ccache introduction and try to speed up builds in some other way (which I do not know yet).

> 3. CI builds chart version 3.xx.yy pointing to OCI 3.xx.yy.zz
>    * NOTE: after this point people on Kubernetes using >3 will get the update

That sounds good a well. But what would then happen if in a later release the semantic 3.xx.yy versioning part will be the same while RaspberryMatic will use a different zz at the end?

> 4. you publish the release

That sounds good. And if we can add the actions/create-release to generate the first draft template I could then just have fill out manually (and perhaps also later semi-automatically) that would help indeed.

> What I do not like from GitHub Workflows is that there does not seem to be a good way to reuse job steps. I expect the a lot of commonality between the CI, snapshots and release workflows. But a common workflow with a lot of _if_ is not great either...

Fully agreed! I really love the GitHub runners/actions stuff, but I also miss some "include" functionality in the workflow design. GitHub hopefully will introduce such a feature in future, so that interoperability between workflows will be more easy and straight forward!

> > I am still unsure if putting "snapshot" and "latest/stable" container versions/packages into the same "raspberrymatic" ghcr.io space is a good thing.
> 
> This is what usually projects do - typically you document in the package list what is the tag strategy for the repository. Also in the release you can point what is the official tag. That being said, there is no real reason why we would not want to put dev versions of the container to a different package repository.

Ok, then we keep the current workflows and continue to push all docker/OCI packages to the same "raspberrymatic" space.

> I am not aware of any storage limits at this point - Docker Hub tends to delete unused ones after a while

GitHub container registry is still in beta AFAIK and things might change. But apart from not knowing about any storage limits I would like to somehow get the raspberrymatic package space cleaned up regularly. Unfortunately there doesn't seem to be a workflow action that can delete packages from ghcr.io automatically. At least I don't know of any. Because that would really help to get this whole raspberrymatic package area better cleanup up from obsolete/old packages.

And perhaps we should at least get the standard CI workflow to stop uploading each docker/OCI build to the raspberrymatic ghcr.io space and just have the nightly snapshot workflow upload new snaphots there like this is done for the other platforms in the releases section of the project? That should make it more consistant. And for development purposes, we could either create a separate "raspberrymatic-dev" ghcr.io entry or (better) just use the artifact uploads the CI workflow creates with every run.

**Comment by angelnu** [comment]
Good - I built the PR according to the above.

Please do check the `.github/release_drafter.yml` since I just took the example template. You can customize it quite a lot: https://github.com/release-drafter/release-drafter

I would have preferred to decouple the OCI and Helm publish to tight them to the publish of the release but I could not find a way to know what tarballs to download for the docker build if that would run in a different step, potentially not even in the same day if you take some time between drafting the release and publishing the release.

For the time being all binaries and containers are build/uploaded in the same workflow. I expect that when you are about to draft the release you would be in an stable phase anyway.

So, ready

**Comment by jens-maus** [comment]
Thanks for the PR (just merged it). I will look over it as soon as I have my self-hosted runner environment finished (still working on getting things settled for it).

What I am still unsure is, if we would really need to re-create the helm charts for every ci workflow cycle. I saw that you changed/fixed the version for the helm chart release in the ci workflow to 0.0.1. Would that mean that 0.0.1 is always a helm chart for the development? If so, the only "issue" I see with this is, that with every CI run it will update the git repository and thus constantly fill it up with old 0.0.1 versions of the helm chart, which isn't nice IMHO.

Regarding when to release the new version. As said, I am currently busy with the self-hosted runners because the github runners - even with ccache - couldn't handle all the load anymore and timed out >6h for some platforms. So I postponed the release already (was planned for this weekend). And indeed, it would be great to have the HA add-on also ready for the next stable release, but this would need some actual hardware testing if a OVA or rpi3 HAos installation with the RaspberryMatic add-on works in principle. Thus, we still need to solve the missing kernel module dependency in HAos. And I am still unsure how to solve it in a quick way (see HA ticket).

**Comment by angelnu** [comment]
I think it would be perfectly ok to not rebuild the dev helm chart for each PR/push and instead upload a container tagged with `raspberrymatic:dev`. Currently it has to rebuild the chart because the dev tag is changing.

On the release: it was not intended as presion at all! I understand what it is working on Open Source in your spare time. I was mostly curious of what you intended to pull in before going with a new release. I understand that you want to switch to the private runners before.

On the HA - IMO this could get into the next one -> I would suggest to first let interested people to manually deploy and provide feedback. We could start with only those using Homematic with LAN GWs until we have figured out the kernel modules as we are discussing in the other threat. The release is already quite large (OCI, Kuberbenetes, official releases, etc) so getting it stable is IMO more important than adding more platforms.

I will see if I can get the kernel module idea working in HA so, if it is ready on time, could get into the release. Not sure were we would want to host this new docker container. I was thinking in github repo, in a separated registry. What do you think?

**Comment by angelnu** [comment]
I think the base Kubernetes support is available to use - if there are any issues with the new CI please open an issue and assign.

@jens-maus - should we ask for feedback in the forum before closing this issue?

**Comment by jens-maus** [comment]
> I think it would be perfectly ok to not rebuild the dev helm chart for each PR/push and instead upload a container tagged with `raspberrymatic:dev`. Currently it has to rebuild the chart because the dev tag is changing.

But is this really necessary at all in practical terms? Why not simply let the helm chart be updated with the nightly build workflow? IMHO it should be enough to have a daily snapshot rather than having each commit end up in helm chart or docker container updates. To me this sound too much of a hassle just for the sake of some additional flexibility which you still get by downloading the corresponding build artifact.

> On the release: it was not intended as presion at all! I understand what it is working on Open Source in your spare time. I was mostly curious of what you intended to pull in before going with a new release. I understand that you want to switch to the private runners before.

I am almost done with the private runners here. I have setup a docker swarm of 40 docker-based runners on a fairly large cluster here which should provide enough resources to get build done in time again. Sorting out the last bits here on that matter and then I can concentrate on the next release. Please note, however, that with switching to self-hosted runners I will have to disable running the workflow execution on pull_requests coming from foreign/forked repositories. This is required to ensure the nessary security for the self-hosted runner environment as normally GitHub explicitly discourages the use of self-hosted runners on public repositories like RaspberryMatic (https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories).
 
> On the HA - IMO this could get into the next one -> I would suggest to first let interested people to manually deploy and provide feedback. We could start with only those using Homematic with LAN GWs until we have figured out the kernel modules as we are discussing in the other threat. The release is already quite large (OCI, Kuberbenetes, official releases, etc) so getting it stable is IMO more important than adding more platforms.

I agree. I also think that after getting the self-hosted runner environment done I will concentrate mainly on getting all things regarding the release done and then potentially just release+announce the new docker/OCI platform as well as the HA Add-on as a beta quality implementation. And then we could use the next release cycle to get the rest of the open things regarding docker / HA add-on implemented afterwards.

> I will see if I can get the kernel module idea working in HA so, if it is ready on time, could get into the release. Not sure were we would want to host this new docker container. I was thinking in github repo, in a separated registry. What do you think? The HA add-on repository is already ready to serve multiple add-ons so that part is "easy".

As said in the other ticket, I am still not sure if your docker container based kernel module installation/build is viable or possible at all in case of HA and if it really helps for the pure docker/OCI installation because there we anyway need the detailed documentation how to manually install the docker container. So this docker container then only partly replaces some steps of the `deploy.sh` script IMHO. Is this really worth the work? I am not sure.
