### ISSUE TITLE
HA proxy is also needed for Kubernetes

### ISSUE THREAD

**Issue by angelnu** [jens-maus/RaspberryMatic#1108]
**Describe the bug**
Access to the WebUI using the default Kubernetes proxy is not reliable - using the ha-proxy originally being developed for Home Assistant address these issues.

In Kubernetes the nginx proxy does not have a fix IP so the hardcoded IP in https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base-raspmatic_oci/bin/ha-proxy.js is preventing its use in K8S.

Could we use the whitelisted IPs configured in the CCU webui to filter what IPs are allowed to connect to the ha-proxy?

**Steps to reproduce the behavior**
connect to the ha-proxy from an IP whitelisted in the WebUI -> 403.

**Expected behavior**
Connection from whitelisted IPs working

Connecting from an IP not whitelisted -> no connection

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: snapshot
 - Used Hardware: x86_64 host
 - Used HomeMatic RF-Module: NA (test env)

**Additional context**
...

**Comment by jens-maus** [comment]
Can you please elaborate more on this kubernetes proxy you are using/referencing? Is there a way to query/know from which IP the K8s proxy might access the WebUI?

And please note, while it would be no problem to add an option to `ha-proxy.js` for providing the IP address, I have also added the same IP limitation to the default WebUI firewall setup (https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base-raspmatic_oci/lib/libfirewall.tcl#L457). Thus, if we add such an option to the docker container we would need to provide this special IP address also to this `/lib/libfirewall.tcl` script so that the iptables-based firewall will allow access to the ha-proxy running on port 8099 as well.

**Comment by angelnu** [comment]
A schematic of the [Kubernetes ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) is
![image](https://user-images.githubusercontent.com/4406403/106383122-5d994e00-63c4-11eb-8aa6-417460035edb.png)

Basically the RaspberryMatic is the POD on the right while nginx is used as the ingress container on the left. The ingress container gets a random IP address within the cluster namespace. By default the cluster IPs are in the 10.* range -> they are in a non Internet routable IPs.

Not sure if it would help but the ingress pod, same as any other pod has a DNS name (served by the Kubernetes DNS server that all containers use). But unfortunately , this name is also configurable in Kubernetes so hard-coded would not be good.

Is there a reason to filter by source IP? I understand that the iptables has to be explicitly configured to permit access to the ha-proxy but is there a security issue requiring the ha-proxy itself to have the hardcoded IP? I ask because the iptables allow to decide opening a custom port or whitelist IPs already.

**Comment by jens-maus** [comment]
> Is there a reason to filter by source IP? I understand that the iptables has to be explicitly configured to permit access to the ha-proxy but is there a security issue requiring the ha-proxy itself to have the hardcoded IP? I ask because the iptables allow to decide opening a custom port or whitelist IPs already.

Well, the reason why I added this 172.x.x.x address to the iptables based firewall setup script and the ha-proxy itself was, that in case the firewall is turned off the additional security for ha-proxy just accepting requests from this particular IP address is still there. And as the HA add-on developer documentation explicitly stated that access to the 8099 ingress port should just be allowed for this IP, I did so.

**Comment by angelnu** [comment]
ok, so if we have an env variable with the DNS name (Which could be the IP address) would work for both use cases (HA, K8S). If DNS names are too hard I would suggest an IP address range (172.x.x.x/32, 10.0.0.0/8, etc). This could also be used to decide when the ha-proxy is needed.

**Comment by jens-maus** [comment]
Well, then suggest an ENV variable which could be supplied to the docker container on startup, then I could change ha-proxy and libfirewall.tcl to query for this ENV variable first and if it exists it will startup ha-proxy and setup the limitation to this variable.

And please note, my long term plan is to get the RaspberryMatic/CCU WebUI changed to always use relative URLs rather than absolute ones and in an optimal case this would then render this whole ha-proxy obsolete.

**Comment by angelnu** [comment]
if you are able to get all moved to relative paths that is really the best option!

For the time what about `WEBUI_PROXY_ALLOWED_CIDR` which must include an IP in CDIR syntax (which should work for iptables quite well). If we agree, I would do a a PR to add to the HA add-on and the Helm chart.

**Comment by jens-maus** [comment]
Feel free to submit a PR. I will then review it and integrate it accordingly.

**Comment by angelnu** [comment]
Ok, will do (not today) . The tcl should have access to the env variables, right? Same for the node.js I would hope.

**Comment by jens-maus** [comment]
It depends were you add the ENV variable. For the HA add-on it works, yes. so the ha proxy startup for example has access to the RUNNING_IN_HA variable because we define it in the add-on configuration so the docker startup manages this.

**Comment by angelnu** [comment]
I would pass it via container methods (so the init process gets it). This methods is the same for all usages of OCI so it will also work for K8S.

**Comment by jens-maus** [comment]
This issue should now be resolved, the ha-proxy now is able to get the CIDR of allowed IPs via the `HM_HAPROXY_SRC` env variable. Thanks for the suggestion and PR!

**Comment by angelnu** [comment]
Thanks for reworking the PR @jens-maus - sorry for missing the variable name change in the commit.

I will prepare a PR to use in the Helm chart once I test it over the weekend.
