### ISSUE TITLE
Prevent downgrade of device firmware

### ISSUE THREAD

**Issue by HolgerJeromin** [jens-maus/RaspberryMatic#1188]
**Describe the bug**
I got a BSM device with firmware 1.18.14 but it is not released yet. But I got an information to downgrade my device.

**Expected behavior**
Prevent or at least warn on an downgrade.
I did not read the message precise because an upgrade of an new device is not unusual if the device was in the warehouse for a few month.

**Screenshots**
![image](https://user-images.githubusercontent.com/2410353/111981561-1f88f280-8b08-11eb-9540-e39a260b7352.png)

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: ccu3

**Additional context**
Same here:
https://de.elv.com/forum/hmip-bsm-firmware-1.18.14-1.18.12-18465

**Comment by jens-maus** [comment]
This is not a bug, but a feature! It has already been discussed several times in the homematic forum that a suggest downgrade is equally valid than suggesting a device firmware upgrade. Due to organizational reasons ELV/eQ3 sometimes ships devices with newer firmware because their HmIP-Cloud infrastructure is already certified for this newer firmware. However, these newer firmware are not certified or tested for the CCU environment. And thus, it is perfectly valid to suggest a firmware downgrade because otherwise the WebUI could probably not correctly work with the newer firmware. Thus, this is a perfectly valid behaviour and you are suggested to actually run this downgrade or you may risk that some functionality does not work as expected.

**Comment by HolgerJeromin** [comment]
In this case I would support a better GUI.
