### ISSUE TITLE
Control Mode will be not sent back to iobroker

### ISSUE THREAD

**Issue by ckoop** [jens-maus/RaspberryMatic#1193]
**Describe the bug**
Control Mode will be not sent back to iobroker if changed via raspberryMatic

**Steps to reproduce the behavior**
1. changed via iobroker, it is sent to raspberryMatic
2. changed via raspberryMatic, it will be not sent back to iobroker
3. if the set point temperaure is changed via iobroker, it sent to raspberryMatic and vise versa
4. changed via raspberryMatic, it will be not sent back to iobroker

**Expected behavior**
the behavior would be that the Control Mode (AUTOMATIC/MANUAL) will sent back to iobroker if changed via  raspberryMatic

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: RaspberryMatic 3.57.4.20210320
 - IOB HomeMatic RPC: 1.14.35
 - IOB HomeMatic ReGaHSS: 3.0.16
 - Used Hardware: Raspi4 4GB, Ubuntu Server
 - Used HomeMatic RF-Module: HmIP-RFUSB

**Additional context**
...

**Comment by jens-maus** [comment]
Please provide more debug information and discuss this matter first in the ioBroker fora so that you can rule out any ioBroker specific issue first with other ioBroker users and developers. And if you have more detailed debug information than simply stating "does not seem to work" you can come reopen this ticket of course.

**Comment by ckoop** [comment]
Hi Jens, sorry for that. You are right to raise it on ioBroker side first.

I found the solution here https://github.com/ioBroker/ioBroker.hm-rega/issues/129#issue-840863288. Read back is already implemented via SET_POINT_MODE
