### ISSUE TITLE
Lan Gateway wird nicht erkannt

### ISSUE THREAD

**Issue by raschl68** [jens-maus/RaspberryMatic#1203]
Seit Patch 3.55.10 wird das Lan Gateway mit der gleichen Version und jeweils auf RaspberryMatic nicht mehr erkannt. Wenn die Lan Gateway Version 3.55.5 ist, wird es wieder, auch von 3.57, erkannt.

Kann das bitte behoben werden?

**Comment by jens-maus** [comment]
Sorry, but the bug/issue ticket you have created does not contain enough detailed information for a thorough problem analysis or you described issue might point out that this could only be an issue in your own installation. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. And if at the end of these discussions other users might have verified your problem, feel free to come back here and open a new tickt accordingly. In addition, please make sure to understand and fill out the provided ticket template or otherwise this ticket will be rejected again.
___
Tut mir leid, aber die Angaben im generierten Issue Ticket sind nicht mit genug technische Details hinterlegt oder deuten auf ein reines Problem in der Nutzerinstallation hin. Bitte beachten, dass dies hier kein Support/Diskussionsforum ist, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen. Dann in diesen Foren bitte das Problem darlegen und mit anderen Anwendern entsprechend diskutieren/analysieren. Und sollte dabei sich ein konkretes Problem bzw. Problemansatz in RaspberryMatic ergeben kann hier gerne ein neues Ticket aufgemacht werden. Dann jedoch bitte das Ticket Template komplett ausfüllen um die Problembehandlung durch Entwickler zu vereinfachen.
