### ISSUE TITLE
Add bash to image

### ISSUE THREAD

**Issue by alexreinert** [jens-maus/RaspberryMatic#121]
I'd like to use some existing shell scripts with CUXD but they are using some bash related stuff. So it would be nice, to have bash in the Raspberrymatic image (Not as default shell, just the precompiled binary)

**Comment by jens-maus** [comment]
I can of course understand your request, however, you also have to understand that I can't all kind of packages users' might need for there own stuff. IMHO an Addon (e.g. CUXd) should come with a bash binary that can be used instead of integrating it for all users that so that 99.9% of users won't require it but still have the binary installed. RaspberryMatic's mission is to be lightweight and not a full-fledged linux distribution with all gimmicks included. However, I will keep that request open for the time being and see how many other users might require that.

**Comment by jens-maus** [comment]
Just forwarded the request for providing „bash“ to the hm-tools“ CCU Addon package (https://github.com/fhetty/hm-tools)
