### ISSUE TITLE
"not enough real-time shares" on HomeAssistant OS

### ISSUE THREAD

**Issue by kegelmeier** [jens-maus/RaspberryMatic#1273]
**Describe the bug**
I upgraded my Home Assistant set-up with RaspberryMatic already running on it before to HA OS 6.0 RC1 and wanted to switch to a set-up with the HM-MOD-RPI-PCB. However, when launching RaspberryMatic with the HM-MOD-RPI-PCB plugged on, RaspberryMatic rfd and HomeMatic IP fail to load. 
Please see the protocol for more context. 
With a HMIP-RFUSB the set-up works just fine.

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: Raspi 4
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying onboard hardware: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.4, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO, HmIP: HM-MOD-RPI-PCB/GPIO, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ERROR: not enough real-time shares (cpu.rt_runtime_us == 0)
Starting rfd: ....................ERROR
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

**Comment by jens-maus** [comment]
This is a currently known limitation of the pre 5.x -> 6.0 HAos upgrade, which after the upgrade to 6.0 seems to require a container recreation of the HA supervisor, which unfortunately is not automatically performed by an upgrade (see https://github.com/jens-maus/RaspberryMatic/issues/1087#issuecomment-839933425). However the HAos devs (e.g. @agners) seem to already work on getting this fixed in a future HAos version.

In the meantime you can simply temporarily switch the supervisor to using a dev channel and then switching back to production. This will trigger the necessary container re-creation and should solve these issues.

**Comment by kegelmeier** [comment]
Thanks! This fixed it. 
Now the devices do not respond - I guess this will take some time according to your input [here](https://homematic-forum.de/forum/viewtopic.php?t=45581) @jens-maus

**Comment by jens-maus** [comment]
> Thanks! This fixed it.
> Now the devices do not respond - I guess this will take some time according to your input [here](https://homematic-forum.de/forum/viewtopic.php?t=45581) @jens-maus

This is only true for HmIP devices, yes. Because if you switch over from a different RF module (with a different serial/SGTIN number) it will require some re-keying over eQ3 servers. Thus, your HA needs an unrestricted internet connection and some time, yes. However, you should be able to see the re-keying in the `/var/log/hmserver.log` logfile.

**Comment by kegelmeier** [comment]
I waited until tonight but nothing changed. I can control the devices however, I cannot see the status of them within the CCU. Also, buttons are not working. Any idea how to fix?

**Comment by jens-maus** [comment]
As said: have a look at `/var/log/hmserver.log`

**Comment by Djgamer123** [comment]
good

**Comment by jens-maus** [comment]
Closing because this issue is about to be fixed by the HAos devs. See https://github.com/home-assistant/operating-system/pull/1368
