### ISSUE TITLE
HM-MOD-RPI-PCB und anlernen des HmIP-DRAP

### ISSUE THREAD

**Issue by Norm71** [jens-maus/RaspberryMatic#1298]
**Is your feature request related to a problem? Please describe.**
Using a Raspberry Pi4 8GB along with HM-MOD-RPI-PCB with the latest Raspberrymatic. Unfortunately I get the message "Die Nutzung eines HmIPW-DRAP oder HmIP-HAP Access Points setzt den Einsatz eines RPI-RF-MOD Funkmodules voraus."

**Describe the solution you'd like**
The EQ3 MOD module should be supported for the DRAP as well

**Describe alternatives you've considered**
NONE

**Additional context**
...

**Comment by jens-maus** [comment]
Well, this is nothing we (the independent RaspberryMatic project) can do about! The whole rf-module development (incl. Firmware) is closed source. Thus, no chance to implement this by us. So please forward your request to eQ3. However, be prepared that you will receive no reaction there because the RPI-RF-MOD is the successor of the HM-MOD-RPI-PCB and thus there will be probably no further firmware updates for it. So time would be better invested in upgrading to the RPI-RF-MOD if you require to add a HmIPW-DRAP or HmIP-HAP!

**Comment by Norm71** [comment]
Thought it was the other way around so I ordered HM-MOD-RPI-PCB instead of RPI-RF-MOD. Will change it! Thanks for clarification.
