### ISSUE TITLE
multimacd causes significant CPU load

### ISSUE THREAD

**Issue by cactus-online** [jens-maus/RaspberryMatic#1324]
**Describe the bug**
after a running period of day's ( one or two weeks ) the multimacd causes significant CPU load
```
Mem: 729056K used, 249664K free, 5564K shrd, 28344K buff, 187560K cached
CPU:  14% usr  15% sys   0% nic  69% idle   0% io   0% irq   1% sirq
Load average: 2.19 2.13 2.44 5/275 11513
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  895     1 root     S<   12216   1%  24% /bin/multimacd -f /var/etc/multimacd.conf -l 4
```
This causes a huge count of service messages. And response times for CCU triggered actions become higher.

Not 100% sure, but seems only BidCoS-RF devices affected.

**Steps to reproduce the behavior**
Not clear, what the root cause is. No special activity, log enty in Log-File.

**Expected behavior**
Clear Log-Entry or better, the issue isn't happen.

**Screenshots**
![Servicemeldungen](https://user-images.githubusercontent.com/34659157/123620747-d7feba80-d80a-11eb-9e4c-ce0ed9eabceb.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: Raspberry Pi 3
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Sorry, but this can't be a general problem/issue because for me and several others we are not having any such high CPU load issue with multimacd. So please proceed according to the following statement and please come back if you have others replicating your issue or if you have more technical information pointing the finger at a specific/definite bug.

Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by cactus-online** [comment]
Keep it in mind, it was only for your information.

**Comment by jens-maus** [comment]
Of course, but this is a bug tracker and no discussion fora. Thus, such information (which didn't immediately qualify as a clear bug) is better to be discussed first and then perhaps moved over to the bug/issue tracker if others have reproduced it or if there are clear technical indications for work to do.
