### ISSUE TITLE
Buttons oben/unten not shown for HmIP-SMI55 

### ISSUE THREAD

**Issue by cactus-online** [jens-maus/RaspberryMatic#1325]
**Describe the bug**
Display of the device is incomplete, because only the sensor values (and to buttons for "Bewegungserkennung einschalten" and "Reset Status" which for me not clear recognizeable as buttons) are shown. If I go through "Status und Bedienung" -> Räume much more information are displayed, but the switches marked as "Der Kanal hat hier keine Funktion". 

**Steps to reproduce the behavior**
1. Using webUI

**Expected behavior**
![Ueber_Geraete](https://user-images.githubusercontent.com/34659157/123623131-65dba500-d80d-11eb-9946-11161a58c57f.png)
![UeberRaeume](https://user-images.githubusercontent.com/34659157/123623160-6b38ef80-d80d-11eb-86d1-1a07fa424163.png)

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: Raspberry Pi 3

**Additional context**
...

**Comment by jens-maus** [comment]
Well, this is the usual behaviour. The Buttons up/down channels do not have any functionality within the WebUI. Thus, the Display of "Der Kanal hat hier keine Funktion" is correct because there is no display or functionality to switch the buttons from within the WebUI. And that the status stuff from channel :0 (The maintenance channel) is shown is the expected behaviro and not specific to this device only. Thus, also here: please discuss this first in a discussion fora if you feel there is something wrong here or can be improved and then come back here with more technical details.

**Comment by cactus-online** [comment]
OK, This is a little too complicated for me. If I ask in the forum (snmp-extend), the answer is: "Nope, no one has created an issue yet". If I create an issue, the answer is: "Please discuss in the forum first".

I am out.
