### ISSUE TITLE
Variables on WebUI Startpage are shown twice

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1360]
**Describe the bug**
Variables on WebUI Startpage are shown twice after some time.

**Steps to reproduce the behavior**
1. Refresh WebUI in web browser
2. Variables are shown normal (only one entry for each)
3. Wait some seconds (max 60). ...
4. Variables are shown twice after WebUI updated them automatically
5. After manual update (page change or update from browser refresh) variables are shown normal again until automatic refresh from rasprberrymatic system is performed again.

**Expected behavior**
Variables on WebUI Startpage should not be doubled on internal refresh.
I think this issue was happening min. in one earlier version and had been fixed already.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version:  3.59.6.20210703
<html><body>

  |
-- | --

</body>
</html>
 - Used Hardware: Raspberry Pi 4 Modell B; 4 GB
 - Used HomeMatic RF-Module: HB-RF-USB TK

**Additional context**
...

**Comment by jens-maus** [comment]
Sorry, but you neither provide screenshots or any detailed information here which could help to reproduce the issue. Nevertheless, doubled WebUI elements are a common issue in some rare cases which are caused by some internal cache issues in the WebUI. Nevertheless, a reboot usually solves these issues.
