### ISSUE TITLE
Neo Server Timeout on Home Assistant

### ISSUE THREAD

**Issue by drMaxxi** [jens-maus/RaspberryMatic#1592]
### Describe the issue you are experiencing

I am trying to configure the Neo Server (with the ConfigTool Neo) on Raspberrymatic running in Home Assistant. The ConfigTool is able to find the Server (all ports in the Raspberrymaticsettings of Home Assistant are enabled) but than no changes can be performed. The error message is: “connect ETIMEDOUT 172.30.33.0:8088”. 

### Describe the behavior you expected

The ConfigTool Neo connects to the server and changes can be performed.

### Steps to reproduce the issue

1. Open the ConfigTool Neo and search for the server.
2. Once the server is identified, try to connect and perform changes.
3.
...

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying onboard hardware: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: .......HmRF: RPI-RF-MOD/HB-RF-USB@usb-0000:01:00.0-1.4, HmIP: RPI-RF-MOD/HB-RF-USB@usb-0000:01:00.0-1.4, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.12, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: ............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

**Comment by jens-maus** [comment]
> The ConfigTool is able to find the Server (all ports in the Raspberrymaticsettings of Home Assistant are enabled) but than no changes can be performed. The error message is: “connect ETIMEDOUT 172.30.33.0:8088”.

To me this looks like the NeoServer is transfering the IP information (IP address + port) via an internal protocol between Client+Server. However, as in case of a HomeAssistant use RaspberryMatic is running within a docker container with its internal `172.30.33.0` IP address here it is of course not reachable because that's not the IP address of the HomeAssistant host.

To fix this issue, it looks like Mediola would have to change their protocol or provide a config option somewhere to specify the reply IP address and port manually in case of running a CCU within a docker container. Thus, please raise a ticket with Mediola so that they can help you out here or provide the necessary changes in a future NEO version. And then please report back here if they solved it.
