### ISSUE TITLE
Offline after latest update

### ISSUE THREAD

**Issue by sgc-fireball** [jens-maus/RaspberryMatic#1842]
### Describe the issue you are experiencing

After upgrade, the CCU Matic dont comes up.

### Describe the behavior you expected

The OS can boot

### Steps to reproduce the issue

1. Upgrade
2. Reboot
3.
...

### What is the version this bug report is based on?

3....

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Running sysctl xargs Bad message
...
Irqbalance: start-stop-daemon can't not execute ....
Rngd: start-stop-daemon can't not execute ....
System Message Bus: fail to open config
Iptables error in line 9: iptables-restore: Bad message

On the boot the screen, the last message is:
Starting HMserver.........
```

**Comment by sgc-fireball** [comment]
![Uploading IMG_20220521_114446.jpg…]()
![Uploading IMG_20220521_114741.jpg…]()

**Comment by jens-maus** [comment]
Sorry, but this isn't a discussion fora here but a bug and issue tracker. So please discuss sich local issue in an appropriate user discussion fora instead of raising a bug/issue ticket which certainly isn't a bug in RaspberryMatic.

However, your problem clearly reads like an issue with your used sd card, which in fact might be broken after the update. So please use a completely fresh sd card and install a fresh RaspberryMatic on it and then restore your latest sbk backup. And then please male sure to use an industry like sd card in future (max endurance).

But as said, this is the bug/issue ticket here and no discussion fora. So please route such support request to an appropriate fora instead in future (e.g. homematic-forum.de)
