### ISSUE TITLE
RaspberryMatic silently changes HM-MOD-RPI-PCB firmware

### ISSUE THREAD

**Issue by jampy** [jens-maus/RaspberryMatic#1886]
### Describe the issue you are experiencing

I had a working Homegear installation on a Raspberry 2B with `HM-MOD-RPI-PCB` and wanted to check out Raspberrymatic by *temporarily* install Raspberrymatic on a different SD card.

When switching back to the SD card with Homematic I slowly realized that the setup stopped working due to the HM-MOD-RPI-PCB firmware having been replaced and now being incompatible with Homegear.

### Describe the behavior you expected

I expected that Raspberrymatic would not alter my hardware or at least ask me before doing that.

### Steps to reproduce the issue

1. Have a working Setup with perhaps older HM-MOD-RPI-PCB firmware
2. Run Raspberrymatic
3. Firmware has been altered without any notice

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

Just wanting to let you know this problem. Now I am in a rush to set up Raspberrymatic (with XMLRPC) to get my Homematic gear working again. I think other users would prefer to be informed before any firmware is altered.

**Comment by jens-maus** [comment]
Sorry, but this is intended behavior. RaspberryMatic always makes sure that the rf modules are carrying the right firmware version so that everything works as expected. And there isn't something it has to tell or ask because otherwise it can not properly work.

So sorry if this affected your downgrade to homegear after your endeavor with RaspberryMatic. IMHO this issue should be better reported to the Homegear developers/project because they should actually make sure that the used rf module will carry the firmware version they require, thus perform a firmware downgrade if required. That's IMHO how this should be handled. And BTW, please note, that the firmware homegear is expecting the HM-MOD-RPI-PCB to carry is old and obsolete and limited in functionality compared to the uptodate firmware RaspberryMatic flashes upon bootup.

**Comment by jampy** [comment]
I see and I understand your point.

You know, I probably don't even had used the most recent Homegear version (I used it just as a RPC gateway for my slightly old, custom software that even used BINRPC). It worked fine, in it's isolated environment, without urge to upgrade.

Even a notice in the Raspberrymatic docs (that I did read prior installation) would have helped.

Meanwhile, I was able to make the switch to xmlrpc and Raspberrymatic after a couple of issues. Now I need to pair all devices again, but that's not tragic.

Maybe consider some warning in the docs about fully automated, unattended firmware changes.

BTW, will Raspberrymatic also uprade my devices firmwares automatically?

**Comment by MichaelN0815** [comment]
Have a look into the Changelogs, there you will find the requested Information. 
You could also install an older RM Version, which brings an older Firmware  and it will downgrade automaticly. 

> BTW, will Raspberrymatic also uprade my devices firmwares automatically?

No
