### ISSUE TITLE
Raspberrymatic container/vm without local Homematic Adapter, instead using HmIP-HAP

### ISSUE THREAD

**Issue by fourstone** [jens-maus/RaspberryMatic#1898]
### Describe the solution you'd like

Hello,

Raspberrymatic is installable in a number of flavors, many are VMs/containers without dedicated but shared hardware. Often this shared hardware is not located centrally so additional Gateways are necessary and possible via connection of HmIP-HAP Access points and integrating these into Raspberrymatic.
However this currently only works once a local gateway is already installed, otherwise not even the dialog comes up.

Additional Information: Synology Virtual Machines in the latest release significantly restricted external passthrough device choices so not sure the Homematic USB stick is applicable there still.

Nonetheless it would be great imho to have a container/VM without special hardware running on some central server and provide connection gateways by a number of HmIP-HAP devices spread throughout the house.

I must admit I have no idea how hard it is to enable this, my hope is it would not be a huge task. Can somebody do a rough estimate?

Thanks, Martin

### Describe alternatives you've considered

Just adding a USB Homematic stick and passing it through, however in my setup (cellar with concrete walls and ceiling) this is rather pointless, the HmIP-HAP on the first floor where most the devices are makes much more sense.

Also with Synology Virtual Machines Passthrough is seriously limited in this release, not sure this still works.

### Is your feature request related to a problem?

no problem, pure feature request

**Comment by jens-maus** [comment]
> Raspberrymatic is installable in a number of flavors, many are VMs/containers without dedicated but shared hardware. Often this shared hardware is not located centrally so additional Gateways are necessary and possible via connection of HmIP-HAP Access points and integrating these into Raspberrymatic. However this currently only works once a local gateway is already installed, otherwise not even the dialog comes up.

To quickly summarize your request: You would like to just use a network driven HmIP-HAP somewhere in your network without requiring to also connect a HmIP-RFUSB or RPI-RF-MOD to your host server where your virtual RaspberryMatic runs, right?

I am sorry, but this is not a limitation in RaspberryMatic itself but partly a misunderstanding on your side as well as a technical limitation on the closed software+hardware of eQ3 who develops the whole Homematic eco-system.

The point is, that the HmIP-RFUSB as well as the RPI-RF-MOD is more than just a RF communication device. It is also used to encrypt and decrypt homematicIP packages on-the-fly. That's exactly why it is also sometimes named "co-processor" internally. Thus, it is absolutely necessary that the host system where the RaspberryMatic/CCU operating system runs has access to this co-processor device, thus you need to have a HmIP-RFUSB or RPI-RF-MOD connected. Therefore, this is not a limitation but moreover a feature.

So I am sorry to say, that this is nothing we (the RaspberryMatic project) can work on or change in any way. In addition, eQ3 has absolutely no plans to change these technical dependencies. And last not least I do not see anything bad in having such a HmIP-RFUSB connected for the sake of having it there as the encryption/decryption device for proper HomematicIP communication.

> Additional Information: Synology Virtual Machines in the latest release significantly restricted external passthrough device choices so not sure the Homematic USB stick is applicable there still.

It is. The "restriction" Synology applied does not hinder to have a HmIP-RFUSB directly connected to a virtual machine. It just hinders to have unknown USB devices directly connected to the DSM operating system itself. This is unfortunately a common misinterpretation since the release notes of DSM7 mentioned changes on USB connectivity.

Thus, to sum this up here: I do not see any sense or even chance to get your request satisfied in the near or long future. Therefore I am going to better close it right away and would like to ask you to first check documentation or online foras where this topic has been extensively discussed already in the past!

**Comment by fourstone** [comment]
ok, thanks for the explanation
