### ISSUE TITLE
Ability to resort steps of programs without having to edit / delete others

### ISSUE THREAD

**Issue by sep2li** [jens-maus/RaspberryMatic#210]
I realize this is a user interface enhancement and I'm not sure if this project is aiming at implemeting these if the deviate too much or at all from the legacy Homematic CCU2 feature set. However, the one single annoyance (and it's really the one big one) about the user interface is that I cannot change the order of the individual program steps when editing a program without rework.

Instead, if I want to add in a new line of logic on the top or anywhere except the bottom of the program segment, I need to insert it on the bottom and then delete and re-add all steps above this one below it.

What would be sufficient for me is if in edit mode, there would be a dropdown menu with numbers (1,2,3,...) next to each step that I could modify and upon saving the program, the resort would happen.

This would help, especially with long programs, to keep a better overview over the logic.

**Comment by jens-maus** [comment]
This is indeed something for the WebUI development itself. Thus, while not directly related to RaspberryMatic itself, I will flag it as a potential WebUI enhancement. However, due to the complexity I guess that it would be hard to retrofit this request in the existing WebUI. But perhaps eQ3 is reading here and might consider implementing it or @HMside might actually implement it as a WebUI patch like he did in the past already for other things...

**Comment by sep2li** [comment]
Thanks for your insight and I also hope that someone will patch it in :)

And apologies for posting here without seaching in forum first - seems this has been [requested ](https://homematic-forum.de/forum/viewtopic.php?f=19&t=36328&p=351637&hilit=programme+sortieren#p351637) more than once before me.

BTW, just upgraded to 20171216 and all went smoothly.
