### ISSUE TITLE
Feature request: Different event times for window contacts

### ISSUE THREAD

**Issue by PottiMc** [jens-maus/RaspberryMatic#2233]
### Describe the solution you'd like

It would be good to define different event times for the window contacts implemented in the device settings itself. Maybe 2 different switches to connect to. Since one maybe wants to handle different usage scenarious, i.e. one for an alarm system for which it is best to react immediately and one for heating where one would like to define an event time of 10 minutes or so.

I know it is possible to write a script with timers and connect them differently, but the requested solution would be much easier to handle for non-programmers like me.

### Describe alternatives you've considered

Writing a script for every window contact.

### Is your feature request related to a problem?

No.

**Comment by jens-maus** [comment]
Sorry but something like that is definitely not possible in the context of this OpenSource project simply because all firmwares for the HomeMatic and homematicIP devices are closed source which only the vendor (eQ3) has access to. Thus, please contact eQ3 if you have issues or ideas for device firmware changes since this  is definitely out of the scope of this project.
