### ISSUE TITLE
ReGaHss: Display of session list with IPs instead of a simple „Too many simultaneous connections"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#226]
If the limit for connections to the WebUI of ReGaHss is reached it usually just outputs a "Too many simultaneous connection" error message. To be able to cancel stale connections it would be probably a good idea to display the existing session list with IP and port numbers so that a user can cancel stale sessions.

**Comment by BadenPower** [comment]
Nice feature, provided you are mad about security holes.

**Comment by Motorpsycho123** [comment]
How shall the user  cancel a stale session if he isn't able to create a new session because there are to many of them? As far as I see it, this cannot be done without a session so he must either must be the owner of any open session that he can close manually (eg. by logging off) or he must SSH to the rasperrymatic to cancel the session from the shell somehow. In the first case the user should know himself which sessions he has open and the second case he needs to ssh anyway and can fetch the information from command line. 

Generally I think showing this kind of information to any not authenticated user is not a good idea and requires that you trust everyone in your network. I know that the whole security of homematic somehow relies on the local network beeing secure, but that does not mean there should be created new ones just for convenience. No authentication should mean no information.

I'd suggest to let users increase the session limit to avoid this at all, which i've seen seems to be already implemented.

**Comment by BadenPower** [comment]
> As far as I see it, this cannot be done without a session so he must either must be the owner of any open session that he can close manually (eg. by logging off) or he must SSH to the rasperrymatic to cancel the session from the shell somehow.

 
It's also possible to clear a session by using a simple hm-script-statement on port 8181.

**Comment by jens-maus** [comment]
@Motorpsycho123 Can you please elaborate the potential security problems you think such a session list display would generate? Currently, I can hardly see a severe security problem as long as the session ids are not exposed at the same time.

**Comment by Motorpsycho123** [comment]
I am arguing from a general perspective. No internal data should be visible without authentication and authorization.  I know that homematic/raspberrymatic (at least in its default configuration) currently heavily relies on the local network being a safe space (which starts be not using https) but development target should be to close existing security holes and make it secure even if run in an unsecure environment, at least if the user whishes to configure it for this. 

Regarding your question about the possible attack vectors I must say, that attack vectors are never known until some creative mind starts using them. Having knowledge about connected IP adresses and ports might be the last mosaic an attacker needs to complete his attack. For example an attacker might block you from your system by attacking the given IP addresses on network level (flooding, dos or similar).

Finally I just don't see the real advantage of giving this information public to every unauthenticated user. If a user has the problem to run out of sessions frequently he should increase the session limit. Otherwise and if the user is legit owner he should have other ways (ssh, router information etc.) to get it. 

If you wish to implement it, at least make an option to deactivate it for users who prefer a more secure system over a convenient one.

**Comment by robdg80** [comment]
A compromise may be: 
If the limit for connections to the WebUI of ReGaHss is reached and a new connection should be established, the existing session list should be written to a log which should be accessible via ssh and via WebUI after the next login. The important thing would be that this information is available after a reboot or after a clear of the session list.

Sometimes the CCU is part of a larger environment. To thus other systems accessing to the CCU (Smartphone Apps, Other Systems like FHEM, OpenHab, IOBroker) which in some cases allocating session IDs. So if any of these other systems get into a problem and to thus allocating much more sessions, these information may be helpful.

**Comment by Motorpsycho123** [comment]
I am not sure if I understand the purpose for this. During runtime you can use netstat to see connections and otherwise you can look into your lighttpd-access.log to see whats going on. I would not suggest to create some special/not generic additional logging for this. Normal logging should be sufficient and if it is not one should be able to configure the normal logging for the server accordingly.

**Comment by jens-maus** [comment]
Since integration of better DDoS methods in ReGa (release with 3.47.x) any change in regard to exposing a session list and be able to cancel open sessions seem to be not necessary anymore. Thus canceling this ticket.
