### ISSUE TITLE
Trying to load RaspberryMatic-3.69.6.20230407-rpi3.zip results in SHA256 error

### ISSUE THREAD

**Issue by gmagill** [jens-maus/RaspberryMatic#2281]
### Describe the issue you are experiencing

When trying to install the latest version, either by auto install or manual download and install, I get a SHA256 compute error. The hash does not match.

However, in windows powershell, the hash does match.

### Describe the behavior you expected

I would expect the hash to compute correctly.

Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

PS C:\Users\Jerry> Get-FileHash C:\Users\Jerry\Downloads\RaspberryMatic-3.69.6.20230407-rpi3.zip

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          FF9042DB5157A1F00B62F94DD5727386C1CD7E140EEB35E9E1FB23D455E826AD       C:\Users\Jerry\Downloads\Rasp...

### Steps to reproduce the issue

1. start auto update or download (+check SHA manually) and install.
2. web console shows SHA mismatch on hash.
3. restore from backup solves the issue.
...

### What is the version this bug report is based on?

3.69.6.20230407-rpi3.zip

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Up to now, updates have gone without any issues.
```

**Comment by jens-maus** [comment]
If this happens, I would suggest to change / use a fresh new SD card because this actually tells you that the downloaded image during the update process was not correctly stored on the underlying disk device (probably your sd card). Thus, this might be a clear indication that your sd card will probably have some hardware bit defect or similar. So please replace it any try again.

And if this would be a general error/bug in RaspberryMatic we would definitly see a lot more bugs/issue tickets appearing here and in the discussion fora. Thus, this most certainly is an issue in your installation...

**Comment by gmagill** [comment]
Yes, most likely this is the answer. Thanks.
