### ISSUE TITLE
WebUI: Freeze of WebUI refresh if special characters (\n) are used in system variables displayed as favorites

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#231]
If s system variable contains a special character like `\n` and this system variable is added in the favorite display on the main WebUI page the WebUI is not refreshed anymore and stays unresponsive and the status of service messages and alarm messages stays grey. Removing this special character fixes this problem.

Reference:
https://homematic-forum.de/forum/viewtopic.php?f=31&t=31579#p292128

**Comment by jp112sdl** [comment]
### I would like to expand this issue:

**If a string contains `<br>` instead of `\n`, the line feed is correctly shown under "Status und Bedienung"->"Systemvariable".**
![bildschirmfoto 2018-01-03 um 23 05 38](https://user-images.githubusercontent.com/18190139/34542446-eb37bd2c-f0dc-11e7-90be-b3c5e12c79bc.png)

**If you put the variable on the start page, the content is shown correctly for a very short moment.**
![bildschirmfoto 2018-01-03 um 23 22 46](https://user-images.githubusercontent.com/18190139/34542487-0b53bf20-f0dd-11e7-9b59-3f885b55caf7.png)

**After the page content finished loading, the variable is shown with \<br\>**
![bildschirmfoto 2018-01-03 um 23 21 30](https://user-images.githubusercontent.com/18190139/34542520-34a5fe6a-f0dd-11e7-9dcc-199580e1b9fd.png)
