### ISSUE TITLE
HA Addon still not starting on Odroid M1

### ISSUE THREAD

**Issue by linloen** [jens-maus/RaspberryMatic#2349]
### Describe the issue you are experiencing

Addon still not startting on Odroid M1.

Log:

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.4, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.7.20230626 (raspmatic_oci_arm64)

### Describe the behavior you expected

Addon not hanging on initial screen.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Home Assistant 2023.6.3 Supervisor 2023.06.2 Operating System 10.3 Frontend-versie: 20230608.0 - latest
```

### Additional information

See also closed issue:  HA add-on not starting on Odroid M1 #2299

**Comment by jens-maus** [comment]
After some investigation it seems that this is an issue in the home assistant operation project instead since the kernel of the ODROID-M1 is missing important 32bit emulation instructions (`CONFIG_CP15_BARRIER_EMULATION`) which first need to be integrated there so that the 32bit binaries distributed with the RaspberryMatic add-on can be executed correctly.

**Comment by jens-maus** [comment]
Please note that this issue seems to be solved now with the merged PR in HomeAssistantOS. Once version 10.4 of HomeAssistantOS is released all the necessary services (multimcad, etc.) should now correctly start and work. Please note, that in case you want to already test that you can try with one of the latest nightly development snapshots (see https://os-builds.home-assistant.io/11.0.dev20230627/).

**Comment by jens-maus** [comment]
closing this here since an issue in HomeAssistantOS and already fixed now.
