### ISSUE TITLE
HUE und HomeKit 

### ISSUE THREAD

**Issue by Jedden19** [jens-maus/RaspberryMatic#2650]
### Describe the issue you are experiencing

Since the new update the HUE Connection and the HomeKit App are not working. 
Backup was restored, everything well. But after the new installation of the Update
again, the a.m. devices are not responding.

### Describe the behavior you expected

Running HUE Connection and HomeKit APP

### Steps to reproduce the issue

1. Update to new version
2.
3.
...

### What is the version this bug report is based on?

3.73.9.20240130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by jens-maus** [comment]
This is not an issue of RaspberryMatic, but of the HAP-Homematic Addon which unfortunately is quite unmaintained and outdated at the moment so that I cannot recommend to use it at all anymore, I am afraid.

See here for more info and already existing issue tickets in the HAP-Homematic GitHub project:

https://github.com/thkl/hap-homematic/issues/672
