### ISSUE TITLE
RaspberryMatic als LXC unter Proxmox 8.2.2

### ISSUE THREAD

**Issue by jbaconsult** [jens-maus/RaspberryMatic#2760]
### Describe the issue you are experiencing

Hallo,

ich hab mein Proxmox auf die Version 8.2.2 aktualisiert. Hier werden neue Kernel-Images verwendet (6.8.4-3-pve). Bei der Installation mit dem https://raspberrymatic.de/install-proxmox.sh Script schlägt die Installation als LCX-Container(!) fehl, da der „pivccu-dkms.service" nicht startet. Hier kommt dann folgender Fehler:

ensure_modules.sh[9553]: make -j4 KERNELRELEASE=6.8.4-3-pve ARCH=x86 all...(bad exit status: 2)
ensure_modules.sh[9553]: Error! Bad return status for module build on kernel: 6.8.4-3-pve (x86_64)

Ich hab im pivccu-Repo auch einen entsprechen Bug erstellt, hier als Referenz:
https://github.com/alexreinert/piVCCU/issues/525

### Describe the behavior you expected

Das Installationsscript läuft durch und anschließend ist ein nutzbarer RaspberryMatic LXC-Container verfügbar

### Steps to reproduce the issue

1. Benutzer Proxmox 8.2.2
2. Rufe `wget -qO - https://raspberrymatic.de/install-proxmox.sh | bash -` auf
3. Installation schlägt fehl
...

### What is the version this bug report is based on?

current (live script)

### Which base platform are you running?

generic-x86_64 (Generic appliance, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Installation auf Proxmox mit HB-RF-ETH
```

**Comment by jbaconsult** [comment]
Noch mal als Ergänzung: das Ganze ist wirklich nur bei der LXC-Version. Die VM-Version funktioniert.

**Comment by jens-maus** [comment]
Das riecht mal wieder nach den üblichen Problemen mit den Kernel Headers.

**Comment by agcyl** [comment]
Ich benutzte zwar das install-script nicht - ich denke aber nicht, dass dort das Problem liegt, da das Verhalten schon seit längerer Zeit bei Kernel-Updates von Proxmox besteht. Ich behelfe mir immer mit folgendem "Ablauf" auf dem Host, damit die PIVCCU module korrekt gebaut werden, d.h. erst mal die Module wieder mit dem neuen Header zum Laufen zu bekommen:

1. nach dem Kernel update mit "apt upgrade" bekommt man in der Regel den Hinweis, dass die zum Kernel gehörigen Header nicht installiert wurden. 
Beim aktuell Stand: 
dkms: autoinstall for kernel 6.8.4-3-pve was skipped since the kernel headers for this kernel do not seem to be installed.
2. also ein "apt install pve-headers-6.8.4-3-pve" 
3. Danach sollte ein "dpkg-reconfigure pivccu-modules-dkms" korrekt durchlaufen - aber nicht zu früh freuen - nach einem reboot klappt es interessanterweise nicht mehr :-( 
deshalb nach dem reboot:
4. apt reinstall pve-headers-6.8.4-3-pve   (ganz wichtig "reinstall" !)
5. und nochmal "dpkg-reconfigure pivccu-modules-dkms" - nun sollte es dauerhaft funktionieren - zur Sicherheit noch mal einen reboot durchführen

**Comment by jens-maus** [comment]
Genau diesen HickHack meine ich bzgl Kernel Header Probleme in diesem Kontext.

Und ich denke dieses Problem hier rührt genau vom gleichen Ursprung her: Ein Problem mit den Kernelheadern bzw. dem Bauen der Kernel Module via dkms.

Deshalb würde ich vorschlagen wie üblich zu verfahren und eben wie beschrieben die Kernel Header nochmal von Hand zu reparieren, usw.

Und natürlich darüber nachdenken ob es nicht doch Effekt wäre statt RaspberryMatic als LXC unter Proxmox doch lieber als VM zu betreiben damit man sich diese Kopfschmerzen in Zukunft sparen kann.
