### ISSUE TITLE
Script Read System Variable by Name

### ISSUE THREAD

**Issue by NCC-1701S** [jens-maus/RaspberryMatic#280]
I have a problem with reading systemvariable by name like this:
```
var prop=dom.GetObject("<Name>").Value();
```
Every script stops with this call.

The access with the ID instead the name will work proberly like this:
```
var prop=dom.GetObject("<ID>").Value();
```
Is there any solution?

**Comment by jens-maus** [comment]
Please try the following because my suspicion is that in your system you have a system variable and something else (e.g. a device) with the same name:

```
var prop=dom.GetObject(ID_SYSTEM_VARIABLES).Get("<Name>").Value();
```

That way only the system variables list is searched for a system variable with the name `<Name>` and not the global list which combines all, devices+system variables, etc.
