### ISSUE TITLE
S.USV - Hardwareversion 1.0 not working

### ISSUE THREAD

**Issue by Kroki0815** [jens-maus/RaspberryMatic#297]
Hi,
since a couple of version  after a reboot/update it takes  a very long time to system comes up.
Today i update to the last version and here the same thing.

Now i analyzed the problem: The system hangs on the init-script for the s.usv-daemon (S51susvd).
Here is the susv-client the one who stalles on getting information from the usv-board.

I have the hardware-version 1.0 and it seems that on this version the susv-client from version 2.0 is not working. So i checked the init.script and there is a check for getting the firmware version. But it looks like that the susv-client only work on HW 2.0. 

So the scripts checks only with susv and than stalls on HW 1.0. Here should timeout be used to kill the process after a couple of seconds and then if no version was found the check should be done again with the susv1 client.

The timeout command seems  not in the raspimatic-distribution.

I hope the problem is clear.

Kind regards Thorsten

**Comment by jens-maus** [comment]
This problem is more or less already known. See here:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=39482&start=350#p427524

The problem is, that Olmatic hasn't released a new firmware for the V1 hardware boards to properly support to identify these boards so that during startup the correct firmware will be flashed and thus the correct client/daemon used.

As Olmatic stated, they are about to release a new firmware for the V1 hardware boards including a unified client/daemon for both hardware versions (see https://homematic-forum.de/forum/viewtopic.php?f=65&t=39482&start=360#p427977)

Let's see how long this will take. For the time being, I am afraid but there isn't a smooth solution and you would have to manually modify your `/etc/init.d/S51susvd` script to directly start the `susv1` client binary instead.

**Comment by Kroki0815** [comment]
Ok, thank's for your quick response ... i changed the init-script and for me it's a good workaround .....

**Comment by Gluehwurm** [comment]
New Firmware (V1.40) is here
https://s-usv.de/files/firmware/susv_fw_14_pi.tar.gz

**Comment by jens-maus** [comment]
@Gluehwurm All these firmware files are already delivered with the latest RaspberryMatic version (see `/opt/susvd/fw`). Thus, all a user would have to do is to use the firmware update command to update their S.USV using the well known susv update command in a SSH session.

**Comment by jens-maus** [comment]
This issue has been marked obsolete because time has passed and the content/topic of the issue seem to be not relevant anymore or does not match the current state-of-affairs. Thus, the issue had been closed. If you feel it is still relevant, please update the ticket accordingly with newer information and explain why you feel it is still relevant and should still be taken care of.
