### ISSUE TITLE
Power LED (red) flicker when running RaspberryMatic Image on Raspi3 B+

### ISSUE THREAD

**Issue by dilmash** [jens-maus/RaspberryMatic#358]
I recently installed RaspberryMatic on a brand-new Raspi 3B+. Installation was successful and the performance is really excellent. However I noticed that the power led ist constantly flickering with no specific rhythm. This does not occur when running the newest Debian Stretch image.

The Raspi is powered by a StromPi regulator feed by 9V 2A supply. Checking the voltage with scope and digital meter, I measure a constant voltage of 4.89V without any drop ins.

Are there any known issues with the  RaspberryMatic  image that might cause this to happen?

**Comment by jens-maus** [comment]
> It's not a bug, it's a feature.

That means, as soon as RaspberryMatic has booted correctly the green LED will go into heartbeat mode (faster heartbeat with increased CPU usage) and the red LED will show SD card activity. This also cannot be compare to how Debian Stretch is dealing with the onboard LEDs because this LED blinking/setup scheme is specific for RaspberryMatic.
