### ISSUE TITLE
Raspberry 3 with old interface to Raspberry 3+ with new interface, bootup time 4-5 times longer respect to the old system

### ISSUE THREAD

**Issue by clemz1986** [jens-maus/RaspberryMatic#385]
I've came across a quite strange problem regarding my raspberrymatic installation. 
I have several different raspberry 2/3 with the old interface running and they all do well. I wanted to change some of them to a new raspberry 3+ with the new interface. Initially I've thought the backups are not working at all resulting in a bootloop (deleted here on Github), however I've been digging deeper into the problem in the last 2 weeks and I can confirm that the backups are working but the bootup time is very long about 5-8 minutes with the new 3+ system and the new interface. The exact same backup boots in the old 2 or 3 system with the old interface in about 1 or 2 minutes. Any explanation? On request I can send some backups to test with.

**Comment by clemz1986** [comment]
I've changed the problem description as I could verify with further deeper tests that the backups are OK. Importantly addons do not alter the issue. The bootup times remain long.

**Comment by jens-maus** [comment]
This is a usual behavior for changing between system with different RF modules because there the HMIPServer has to query for new encryption keys for all HmIP devices and this could easily take server minutes to hours. Keep it running for so long and the next few boots should go faster. Nothing to worry about.
