### ISSUE TITLE
Diagramm Feature not anymore useable

### ISSUE THREAD

**Issue by DougJunior** [jens-maus/RaspberryMatic#421]
After the update on the current Version 80922. i can no longer use diagrams.
When i trying to set 1 up or look on my allready existing ones i get the following message.
"Es ist kein USB-Speicher für die Speicherung der Diagrammdaten vorhanden oder auf diesen konnte nicht zugegriffen werden. Um die Diagrammdaten zu speichern, ist externer USB-Speicher erforderlich. "
No USB Stick plucked in, but needed, i have a 32 gb sd card. Why should i plug in a usb stick, when its worked just fine for months without a issue.

**To Reproduce**
1. Einstellungen
2. Click on Diagramme
3. See error

**Expected behavior**
Like in previus Version that i can use it without a usb stick.

**System information (please complete the following information):**
 - Version RaspberryMatic 3.37.8.20180922
 - Hardware RaspberryPi3 B+

**Comment by jens-maus** [comment]
It‘s not a bug, it‘s a feature! Like in the CCU3 firmware this was changed because saving diagrams on the sd card poses too much traffic on the card which will result in a reduced lifetime. Manx users had broken sd cards in the past, thst‘s why this was changed. So please plug a USB stick to get diagrams working again. As a gimmick this will also provide atomatic backups being stored on the stick as well.

**Comment by lobocobra** [comment]
Hi, I start my Raspberry from a SSD, how can I  activate diagram without an USB stick?
