### ISSUE TITLE
Addon update notification not working properly but with CCU3 ok

### ISSUE THREAD

**Issue by clemz1986** [jens-maus/RaspberryMatic#554]
**Describe the bug**
The notification for certain addons (built for CCU3/raspberrymatic) does not work correctly. Please see the screenshot in attach. The new version is replaced by a "n/a" For some addons it is working with the raspberrymatic, for others not. However the same problem does not occur with a CCU3 ("aka original firmware"). I've contacted already the developer of the addons, they replied that this should be a bug in the raspberryfirmware as it is working well on the CCU3

**To Reproduce**
1. Open the addon installation page (Zusatzsoftware) in the Settings. The above described problem is visibile as described above and depicted in the screenshot.

**Expected behavior**
The new version should be announced correctly like it does on the CCU3 original firmware.

**Screenshots**
<img width="862" alt="bildschirmfoto 2019-02-10 um 12 35 39" src="https://user-images.githubusercontent.com/26635485/52533185-71a79900-2d30-11e9-9488-a0d46bd6f936.png">

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.41.11.20190126]
 - Hardware [e.g. RaspberryPi3]
 - (comparison with CCU3 3.41.11 firmware)

**Comment by jens-maus** [comment]
I am sorry, but this is not a bug in RaspberryMatic. Actually in some future version of CCU3 the security change that results in this behaviour will also be ported to the CCU3 firmware and thus, these addons will then show the same behaviour like in current RaspberryMatic versions. Please note that RaspberryMatic is more or less a more uptodate firmware with changes that will be sooner or later ported to the CCU3 firmware.

The reason that for these add ons only "n/a" is shown is, that the update check script these add ons are using are NOT sending any valid "Content-Type:" header. For older versions this weren't an issue because RaspberryMatic/CCU was not sending a specific config setting to the web browser to only allow display of pages with proper content-type headers. But with recent versions RaspberryMatic and thus an upcoming CCU firmware will enforce such a setting to improve security in general.

So please see/note the following changes required to fix these "update-check.cgi" scripts:

https://github.com/jens-maus/hm_pdetect/commit/02fdb6aaed2429fc24326e66f8d81c60051f278e#diff-da639476a433e1b913708991dfd10947
https://github.com/jens-maus/hm_pdetect/commit/dd36d09471795068ee877d035560701be790c7b5#diff-da639476a433e1b913708991dfd10947

And here the link to the complete example `update-check.cgi` script that works for RaspberryMatic and CCU3 as well as for CCU2:

https://github.com/jens-maus/hm_pdetect/blob/master/addon/www/update-check.cgi

So please inform the authors of the addons with non working update checks and send them a link to this explanation so that they can fix their update check scripts accordingly. For all the addons that are publicly available on GitHub or under my control I already fixed the latest versions of these addons already.

**Comment by clemz1986** [comment]
Thank you very much for your immediate answer and the precise indications to fix the issue. I've already informed the developers indicating this thread.
