### ISSUE TITLE
BINRPC to port 2001 not working through lighttpd proxy

### ISSUE THREAD

**Issue by sptim** [jens-maus/RaspberryMatic#557]
**Requests using the binary variant of rfd's xml-rpc api doesn't get a response.**

After migrating from yahm to RaspberryMatic Homebridge stopped working for BidCos devices. HmIP devices kept working. Sniffing the traffic showed that Homebridge is sending binrpc requests and does not get any responses.

**System information:**
 - Version: RaspberryMatic 3.41.11.20190126
 - Hardware: RaspberryPi3 B+, RPI-RF-MOD (Charly)

**Workaround**

Bypass the lighttpd proxy by logging in via ssh and entering

```
iptables -t nat -I PREROUTING -p tcp --dport 2001 -j DNAT --to :32001
iptables -I INPUT ! -i lo -p tcp --dport 32001 -j ACCEPT
```

**Comment by jens-maus** [comment]
"This is not a bug, but a feature!"

Since CCU Firmware version 3.41.x BINRPC is considered to be somewhat obsolete when being used against a CCU/OCCU/RaspberryMatic. All third-party applications are asked to switch to XMLRPC as soon as possible. This is due to the fact that by using BINRPC there is no way to enforce SSL/TLS encryption as well as there is no possibility to provide authenticated RPC calls. Therefore all external apps (including Homebridge) are asked to retire BINRPC as the protocol to be used to query/set information on a CCU device.
