### ISSUE TITLE
Program not executed and STACK_BUSY error message when multiple programs are running concurrently 

### ISSUE THREAD

**Issue by nRaecheR** [jens-maus/RaspberryMatic#558]
**Describe the bug**
When multiple programs are triggered concurrently  (e.g. Sun Rise) some actors aren't switched and in /var/log/messages an error message appears stating that the stack is busy.

**To Reproduce**
1. Setup latest RasperryMatic with multiple (~10) HMIP-BROLL actors
2. Create a programs per actor triggered by Sun Rise event that checks the current visibility status of the actor then changes the visibility from 0 to 100%
3. Occasionally some of the programs seem to fail silently (no error/service message in WebGUI) but then an error message will be logged in /var/log/messages

**Expected behavior**
All programs are running as expected

**Screenshots**
Here is a snipplet from the /var/log/messages log : 

```
Feb 19 09:00:02 RaspberryMatic local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =setValue Params = {"001118A99C9397:4","LEVEL",1.000000} result= [faultCode:-1,faultString:"Generic error (STACK_BUSY)"] [iseXmlRpc.cpp:2605]
Feb 19 09:00:02 RaspberryMatic local0.err ReGaHss: Error: IseXmlRpc::CallSetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1502]
Feb 19 09:00:02 RaspberryMatic local0.err ReGaHss: Error: IseHssDP::WriteValue: CallSetValue failed; address = 001118A99C9397:4 [iseDOMdpHSS.cpp:76]
```

**System information (please complete the following information):**
 - Version : RaspberryMatic 3.41.11.20190126
 - Hardware : Raspberry Pi 2

**Comment by jens-maus** [comment]
The returned faulString with the message "Generic error (STACK_BUSY)" is nothing ReGaHss has any reference to. This is the return code/message returned by the corresponding HmIP device or HmIPServer (in your case the device with SGTIN 001118A99C9397). That means, when RaspberryMatic/ReGaHss was trying to set the "LEVEL" on channel 4 to "1.0" the device/HMIPServer returned with this generic error signaling that too many events were sent at the same time and thus it could not process them anymore. IMHO this is no bug but an obvious limitation in event processing. However, this is clearly an upstream problem RaspberryMatic cannot solve but would require eQ3 to investigate this issue. So please open a bug report at the eQ3 webpage with reference to this issue here. In the meantime you could simply try to add certain delays in sending out device calls in your WebUI programs.
