### ISSUE TITLE
Only upload the firmware to a device if the firmware to upload is newer then the existing firmware version

### ISSUE THREAD

**Issue by holzhannes** [jens-maus/RaspberryMatic#567]
**Describe the bug**
I have some HMIP-SWDO in my RaspberryMatic with firmware 1.16.8 and one with firmware 1.10.7 the only available Firmware from eQ-3 AG is 1.12.2. If I add this firmware to RaspberryMatic it will also be uploaded to the devices with the firmware 1.16.8.

**To Reproduce**
1. Integrate min. two HMIP devices with different firmware versions and min. one version in between for example one with v1 and v3. 
2. Upload a firmware with the Version between the two: v2
3. The Firmware v2 will be uploaded to both devices.

**Expected behavior**
It should be only uploaded to the device which has the older Firmware v1

**Screenshots**
Sorry to late I had to chancel the Upload. 

**System information (please complete the following information):**
 - Version: 3.37.8.20180922
 - Hardware: RaspberryPi Zero W

**Comment by jens-maus** [comment]
Sorry, but this is a feature and not a bug. Firmware downgrades HAVE to be possible for known reasons. So of course a user have to take care to upload the correct firmware. And if he/she upload an older firmware the CCU can do nothing but of course perform a downgrade of the firmware. This is a wanted behaviour and anyway not something RaspberryMatic itself can change!

**Comment by jens-maus** [comment]
Also please not additionally: If eQ3 have only released a lower firmware version for some devices to be connected to a CCU than this is the firmware version the device was tested with a certain CCU firmware release. So IMHO you should downgrade the device to the firmware Eq3 provides for the latest CCU firmware version because otherwise some functionality of the device might not work correctly in the CCU because the CCU might not support some additional channels or changed behavior.

**Comment by holzhannes** [comment]
Thank you very much for your Feedback. The concept of downgrading was not in my mind while writing this 😄 . Thank you also for your hint do downgrade.
