### ISSUE TITLE
RaspBee support?

### ISSUE THREAD

**Issue by mariusmuntean** [jens-maus/RaspberryMatic#63]
Hi,

Any plans to support RaspBee?
Raspbee Homepage: https://www.dresden-elektronik.de/raspbee/

**Comment by jens-maus** [comment]
There are currently no plans to support this ZigBee Module. One problem would probably be that the RaspBee Software would need to be integrated into the buildroot-Linux environment somehow because RaspberryMatic is using buildroot-Linux and is a Debian-based Linux OS. Nevertheless, this should be possible of course. But as said, there are currently no plans to support it in the near future. I also doesn't own such a module here, so I can not implement it myself anyway.

If you feel, however, you would like to contribute support for this, feel free to submit a pull request and I would of course help you in integrating support for it.

**Comment by jens-maus** [comment]
Supporting Raspbee directly in RaspberryMatic doesn't make sense since this is a HomeMatic control station.
