### ISSUE TITLE
Sort Execution in Program

### ISSUE THREAD

**Issue by andinagl** [jens-maus/RaspberryMatic#660]
**Is your feature request related to a problem? Please describe.**
When I edit programs and install new executions with delays, they are not sorted by delay in the program. This makes the programs cluttered (example for programs that run only once a day and includes over 20 executions)

**Describe the solution you'd like**
A sort via automatic or button in the program after execution delay would make the programs clearer

**Describe alternatives you've considered**
---

**Additional context**
I hope the problem is synonymous without screenshot understandable

**Comment by jens-maus** [comment]
This issue has been marked obsolete because time has passed and the content/topic of the issue seem to be not relevant anymore or does not match the current state-of-affairs. Thus, the issue had been closed. If you feel it is still relevant, please update the ticket accordingly with newer information and explain why you feel it is still relevant and should still be taken care of.
