### ISSUE TITLE
Support querying status of HDMI-devices with libCEC

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#68]
libCEC allows to query the status of HDMI-devices that are connected to a RPi. This allows to e.g. switch a Homematic system-variable like "TV" between on/off when the TV is switched on/off. This can be used to e.g. close the shutters of dazzling windows when the TV is on or switch the subwoofer on/off with an AVR.

**Comment by jens-maus** [comment]
@renne First of all, thanks for your suggestion. However, I think it is rather a very rare case where people want to directly connect their RaspberryPi to a TV while at the same time running it as their main CCU using RaspberryMatic. Usually RaspberryMatic should be used as a self-contained server somewhere at the basement and near a UPS system so that the home automation isn't at risk that it is down for a while. Connecting it directly to a TV set is IMHO really a very rare and unusual case. Thus, directly supporting/shipping libcec with RaspberryMatic seems to be somewhat overkill IMHO. However, I will flag this ticket as an enhancement ticket with low priority and being undecided so that in future some people might comment on that if they are also want this kind of functionality.

**Comment by jens-maus** [comment]
Closing this issue as "wont fix" because I still beliebe that this feature would better fit into a proper CCU Addon package to supply this functionality.
