### ISSUE TITLE
RaspberryMatic 3.47.15.20190831: Duty Cycle steigt bis 100% in 10 Minuten

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#693]
**Describe the bug**
After installing RaspberryMatic 3.47.15.20190831 the Duty Cycle of the Pi3+ went up in 10 Minutes to 99%. Before the Duty Cycle was never more than 40%. Also the ELV LAN Gateway is climbing up to over 50%. Was before never more than 15%. This happened now three times.

**To Reproduce**
1. Install RaspberryMatic 3.47.15.20190831
2. Wait and watch Duty Cycle on Startseite

**Expected behavior**
Duty Cycle behavior as in previous version of RM

**Screenshots**

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.47.15.20190831
 - Hardware: RaspberryPi3+

**Additional context**
Interesting fact was that the DC jumped from 99% to 28% and then climbed up again to 99%
After opening the Programme Tab the WebUI crashed (red steady light at the Radio Interface) and the WebUI showed "Die Raspberry Matic ist noch nicht bereit"

**Comment by jens-maus** [comment]
Sorry, but changes in raised DutyCycle are usually not caused by system updates like this but most probably caused by other things, e.g. Devices with low batteries going crazy. So sorry, but you are currently the only one with such issues and neither the betatesters nor myself are seeing systematic symptoms like you report here.

**Comment by friedpa** [comment]
You are right.
