### ISSUE TITLE
Alle Monit-Checks via WebUI konfigurierbar machen

### ISSUE THREAD

**Issue by Troubadix** [jens-maus/RaspberryMatic#700]
**Is your feature request related to a problem? Please describe.**
Es ist etwas verzwickt, alle möglichen Monit-Checks zu konfigurieren bzw. in Teilen unmöglich(?)
Mit der neuen Version kann eine Textdatei angelegt werden, die den Internet-Check komplett abschaltet. Den Schwellwert zu ändern, z.B. erst nach 30 Min Netzausfall zu alarmieren, scheint es aber nicht zu geben.

**Describe the solution you'd like**
In der WebUI sollte ein neuer Menüpunkt eingeführt werden, über den alle Monit-Checks individuell konfiguriert werden können, z.B. Internet-Check 5 Minuten, 15 Minuten, ganz aus. CPU-Last x Minuten, ganz aus usw

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Danke für den ChangeRequest. Bitte aber beachten das dies natürlich viel Aufwand bei wenig Nutzem bedeutet (Otto-Normal-Verbraucher brauch/soll nichts an den Monit checks modifizieren). Wenn also gerne jemand genug eigene Freizeit hat bitte einfach vortreten und einen PullRequest dazu einsenden, denn alleine kann ich das nicht umsetzen und möchte mich lieber auf wichtigere konzentrieren.

**Comment by jens-maus** [comment]
This issue has been marked obsolete because time has passed and the content/topic of the issue seem to be not relevant anymore or does not match the current state-of-affairs. Thus, the issue had been closed. If you feel it is still relevant, please update the ticket accordingly with newer information and explain why you feel it is still relevant and should still be taken care of.

**Comment by mikefjim** [comment]
Hallo Jens,

I'm not sure if it is ok to use this change request or if I should open another one.

I've recently migrated my RaspberryMatic from a PI3 to a NUC running HomeAssistant. 

Since I can now run other services in parallel, specially Motioneye, which consumes a lot of CPU resources, the CPU temperature is sometimes above 80° C, when the watchdog of Raspberrymatic causes a restart. For a NUC 80° C is nothing and it RaspMatic should run without issues.

I followed the instructions to use Monit, but could not yet use it, as RaspMatic is inside HA, but anyway, from what I read Monit doesn't allow to change the Watchdog settings, such as change the CPU temperature threshold.

Do you have any suggestion or any plans for this issue?
