### ISSUE TITLE
add oathtool for amazon alexa authentication

### ISSUE THREAD

**Issue by bhuertgen** [jens-maus/RaspberryMatic#795]
**Is your feature request related to a problem? Please describe.**
Can you add the oathtool to the linux for alexa script authentification ?

**Describe the solution you'd like**
I think you can find the code here....
https://gitlab.com/oath-toolkit/oath-toolkit/tree/master

**Describe alternatives you've considered**
can not find a binary for this linux image

**Additional context**
For using this script 
https://blog.loetzimmer.de/2017/10/amazon-alexa-hort-auf-die-shell-echo.html

**Comment by jens-maus** [comment]
Sorry, but I think this tool (`oauthtool`) would be better suited in a dedicated/separate CCU-Addon package instead of directly bundling it into RaspberryMatic for everyone since only a minor amount of users would require it constantly. Thus, I would suggest to create a separate "oauthtool CCU Addon" package or ask the author of the hm-tools CCU Addon package (see https://github.com/fhetty/hm-tools) to include `oauthtool` in a future addon version.
