### ISSUE TITLE
Bug wenn Session abgelaufen ist

### ISSUE THREAD

**Issue by Xento** [jens-maus/RaspberryMatic#846]
**Describe the bug**
Wenn die Session abgelaufen ist, kommt es manchmal vor, dass man auf die Sicherheitseinstellungsseite weitergeleitet wird.
Dort kann man dann auf Express oder Benutzerdefiniert klicken und sieht dann die Standardeinstellungen auf der Seite.
Wenn man nun die Einstellungen übernehmen möchte, landet man auf einer blauen Seite.
Wenn man nun die Seite neu lädt, erhält man die Meldung das die Sitzung ungültig ist.

**Expected behavior**
Meldung, dass die Session abgelaufen ist und man sich erneut anmelden muss.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1299397/82760701-9e80a200-9df5-11ea-82a8-35d3531f9d98.png)

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by mike-bee** [comment]
+1
Thought that's a feature.
Observing this behaviour with every release since mid 2019.
Workaround: Page refresh

**Comment by jens-maus** [comment]
Sorry, but please provide a more detailed explaination of the issue and some reproducible case with a step-by-step explaination how to reproduce it so that we can try to follow this documentation and analyze/debug it accordingly. Just with the explaination given you are just stating the symptoms but not how these symptoms can be reliabably reproduced.

**Comment by TinkyWonky** [comment]
I run into this regularly, but unfortunately, I was unable to find a way to reliably reproduce.

It happens just casually when I check some diagram or device, leave the browser and device be for some time and reopen it later. I use chrome for home automation issues exclusively, twice a day. The tab neither shows the last webpage state as it does on a computer nor does it state that the session timed out. Without any user interaction, it shows the security settings dialogue as shown by Xento. The URL _probably_ includes the old session id because reloading the page shows the 'session timed out' notice.

Perhaps this rings a bell for anybody?

Device: Google Pixel 2
Browser: Chrome 81.0.4044.138

**Comment by jp112sdl** [comment]
> I was unable to find a way to reliably reproduce.

https://homematic-forum.de/forum/viewtopic.php?f=65&t=59976&p=594511#p594511
