### ISSUE TITLE
ReGaHss: Support for raw string literals

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#848]
**Is your feature request related to a problem? Please describe.**

Especially when using system.Exec(), special characters (e.g. `"` or `\` ) in command line parameters often have to be complexly encoded. This is time-consuming and error-prone.

**Describe the solution you'd like**

For this case a raw string literal is useful. All characters or bytes within delimiters (e.g. `""""` ) are transferred unchanged into the string. Special characters (e.g. `"` or `\` ) are not interpreted. 

**Additional context**

This feature would also be useful for using feature #847.

**Comment by jens-maus** [comment]
While this indeed could make script management and use of system.Exec() in complex cases more easier, I think that this is not possible because the language parser does not differentiate between e.g. system.Exec() use and other function uses like WriteLine(). Thus, escaping special characters with `\` and `"` / `'` will always be necessary or otherwise the top-level parser of the script language can not identify which portion of a statement belongs to the function call and which one should belong to the function parameter.

**Comment by mdzio** [comment]
It is generally intended to be a second way to define character strings. The functionality should not be system.exec() specific:

Examples:
```
string in="""{
  "a": 123,
  "b": "c"
}""";
```

```
WriteLine("""First line
Second line""" +  "\nThird line");
```

**Comment by jens-maus** [comment]
@mdzio Thanks for the example. In fact, this reminded me of something that already exists in ReGa and that might solve your problem/wish. In the ReGa skript language there exists a so called "super string" and that is the `^` character. By using the `^` character anything between two of these character will be taken literal without applying any escaping, etc.

So something like this should be possible:

```
string a=^{ "a": 123, "b": "c"}^;
WriteLine(a);
```

However, please note, that due to limitations in the WebUI you cannot currently use the `^` character in the script editor of the WebUI (see https://github.com/jens-maus/RaspberryMatic/issues/225). Nevertheless, the following `curl` execution should demonstrate that the `^` super string actually works for your example:

```
curl -s -X POST http://192.168.5.244:8181/rega.exe --data 'string a=^{ "a": 123, "b": "c"}^; WriteLine(a);'
```

This in fact creates the following output:
```
{ "a": 123, "b": "c"}
<xml><exec>/rega.exe</exec><sessionId></sessionId><httpUserAgent>User-Agent: curl/7.68.0</httpUserAgent><a>{ &quot;a&quot;: 123, &quot;b&quot;: &quot;c&quot;}</a></xml>
```

Does this already solve your problem?

**Comment by mdzio** [comment]
Yeah, that's exactly what I was looking for. Now all that's left to do is solving #225.
