### ISSUE TITLE
WebUI: Backup upload file size is 0 bytes

### ISSUE THREAD

**Issue by armin34320** [jens-maus/RaspberryMatic#857]
**Describe the bug**
'Backup erstellen' via WebUI.

![Download](https://user-images.githubusercontent.com/47714897/84652755-7247d500-af0c-11ea-930a-5736d8dc3716.PNG)
![Download-Save](https://user-images.githubusercontent.com/47714897/84652758-72e06b80-af0c-11ea-916a-5a857b3b2ee2.PNG)

Download shows correct expexted name for backup file but with 0 Bytes in Firefox . Cannot make a screenshot for the dropdown menu.

**System information (please complete the following information):**
 - RaspberryMatic 3.51.6.20200613
 - TinkerboardS

**Additional context**
Problem existed also in previous version of Raspberrymatic.

if I login to the  RaspberryMatic  I see the following:

![Backup-on-CCU3](https://user-images.githubusercontent.com/47714897/84653093-0a45be80-af0d-11ea-88de-b7fe900e36b7.PNG)

I suppose that the last_backup file is not renamed to the file being downloaded.

**Comment by jens-maus** [comment]
@armin34320 Sorry, but what is the actual problem? That the downloaded sbk ist only 0 bytes large after download? Well, to me this looks like a Firefox, Virusscanner, etc. problem because in the first popup you can see that Firefox itself says the download file is supposed to be 99.2 MB large, thus the CCU/RaspberryMatic itself provides the sbk correctly to firefox. So please use another browser (e.g. Chrome) and see if this solves your issues.

**Comment by armin34320** [comment]
Just tried with Chrome.

![Download-Chrome](https://user-images.githubusercontent.com/47714897/84656689-5f84ce80-af13-11ea-8f3f-85a78a490b08.PNG)
![Download-Chrome-pending](https://user-images.githubusercontent.com/47714897/84656694-601d6500-af13-11ea-981f-b135bd2e2ddd.PNG)

Download will not finish.

**Comment by jens-maus** [comment]
@armin34320 Sorry, but to me this looks like a user/network problem on your end. At least chrome is downloading something which in fact clearly shows that the backup download routines seem to work (providing data to Webbrowser). So please go to the homematic forum and try to discuss your user issue there potentially identifying the root cause of the issue. But as far as RaspberryMatic development goes I can not identify any issue also since I can perfectly download backups here with any browser type I try.
