### ISSUE TITLE
Pimoroni Fanshim: Temperaturwerte konfigurierbar machen / make temperature thresholds configurable

### ISSUE THREAD

**Issue by Ecky78** [jens-maus/RaspberryMatic#868]
**Is your feature request related to a problem? Please describe.**
Bisher ist die Unterstützung für den Pimoroni Fanshim quasi "digital", d.h. man kann sie lediglich aktivieren oder deaktivieren, die Temperaturschwelle ist fest vorkonfiguriert.

Meine Anregung wäre nun, das einstellbar zu machen. Es gibt Einbausituationen, wo der Raspi beispielsweise in einem Hutschienengehäuse kaum unter die voreingestellten 50°C zu bekommen ist. Praktisch bedeutet das, daß der Lüfter dort dann den ganzen Sommer über durchläuft. Ich würde daher gerne die Ein- und v.a. Ausschaltgrenze etwas höher legen, beispielsweise 68°/ 58°C, sodaß der Lüfter lediglich die Temperaturspitzen abfängt. 

**Describe the solution you'd like**
beispielsweise über eine Config-Datei, die mit den Default-Werten vorkonfiguriert, vom User aber änderbar ist

**Describe alternatives you've considered**
(-)

**Additional context**
(-)

**Comment by jens-maus** [comment]
Thanks for this enhancement ticket. However, this isn't so easily possible yet because RaspberryMatic is currently only using an already existing C application daemon for the fan control (see https://github.com/flobernd/raspi-fanshim/blob/master/examples/FanshimService.c). And the 65C / 55C thresholds are actually hardcoded there (https://github.com/flobernd/raspi-fanshim/blob/master/examples/FanshimService.c#L111-L113). Thus, we would need to integrate a patch that would allow to set these limits somewhat. But that of course requires some development, I am afraid. And that takes time.
