### ISSUE TITLE
Glances – Linux System Monitoring Tool

### ISSUE THREAD

**Issue by tempo3** [jens-maus/RaspberryMatic#885]
Hello, how is it possible to install the Linux system monitoring tool "Glances" on the Raspimatic? I have not found any option. Thank you in advance for the support. Best greetings and a big compliment for the super development!

**Comment by jens-maus** [comment]
Sorry, but this is IMHO a "nice-to-have" tool which should not be directly integrated in RaspberryMatic for everyone but delivered as part of a third-party CCU Addon like hm-tools (https://github.com/fhetty/hm-tools). So please forward your request to the hm-tools addon package maintainer @fhetty so that he might integrate that into a future version of the Addon package.
