### ISSUE TITLE
Add option to disable LEDs of homematic device

### ISSUE THREAD

**Issue by lacalamine64** [jens-maus/RaspberryMatic#998]
**Is your feature request related to a problem? Please describe.**
Not really, no.

**Describe the solution you'd like**
Implement the option to disable the device LED on other devices such as HmIP-PDT as well.

**Describe alternatives you've considered**
...

**Additional context**
As my son tends to press all kinds of glowing buttons, he also likes the ones on HmIP devices. I found an option to disable the device LED on my HmIP-PS pluggable switch but on no other device such as HmIP-PDT pluggable dimmer.

![IMG_0442](https://user-images.githubusercontent.com/50332265/100497385-8e0e0300-315b-11eb-9616-7bc54a47edda.jpeg)
![IMG_0443](https://user-images.githubusercontent.com/50332265/100497388-923a2080-315b-11eb-9154-0d3328b81260.jpeg)

**Comment by jens-maus** [comment]
This issue is actually not solveable by the RaspberryMatic project itself because this functionality depends on firmware development/changes by eQ3 and forneach single device required. Thus, it is not easily possible and might require so much time that your son might already been grown up enough to keep his fingers off.

However, I will keep this issue as an upstream issue for eQ3 to be considered/solved instead. So please don't expect something to happen here from RaspberryMatic itself.
